/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config wrangler.jsonc --env-file cloudflare/.dev.vars.example --strict-vars=false --include-runtime=false` (hash: 802e264bbc8948a0580ae047169087e4)
interface __BaseEnv_Env {
	DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	DELENDA_MAINTENANCE_MODE: string;
	DELENDA_ADMIN_EMAILS: string;
	DELENDA_REPLICATION_TOKEN: string;
	SSH_AUTHORITY_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DELENDA_MAINTENANCE_MODE" | "DELENDA_ADMIN_EMAILS" | "DELENDA_REPLICATION_TOKEN" | "SSH_AUTHORITY_SECRET">> {}
}
