/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config wrangler.jsonc --env-file cloudflare/.dev.vars.example --strict-vars=false --include-runtime=false` (hash: 8f6732d95cc4c2e03fef3efbf546589c)
interface __BaseEnv_Env {
	DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	DELENDA_AUTH_PROVIDER: string;
	DELENDA_MAINTENANCE_MODE: string;
	DELENDA_SESSION_SECRET: string;
	DELENDA_ADMIN_EMAILS: string;
	DELENDA_ADMIN_KEY: string;
	CF_ACCESS_TEAM_DOMAIN: string;
	CF_ACCESS_AUD: string;
	DELENDA_REPLICATION_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DELENDA_AUTH_PROVIDER" | "DELENDA_MAINTENANCE_MODE" | "DELENDA_SESSION_SECRET" | "DELENDA_ADMIN_EMAILS" | "DELENDA_ADMIN_KEY" | "CF_ACCESS_TEAM_DOMAIN" | "CF_ACCESS_AUD" | "DELENDA_REPLICATION_TOKEN">> {}
}
