import { accountDayKey, millisecondsUntilNextAccountDay } from "./account-time";

export type Aphorism={id:string;text:string;source:string};
export const APHORISMS:Aphorism[]=[
  {id:"Q001",text:"A commander who spends his reserve early has exchanged uncertainty for regret.",source:"Comm. Het Claxton, Command Ethics Appendix"},
  {id:"Q002",text:"The purpose of a reserve is not to remain intact.",source:"Comm. Het Claxton, Praetor Corps, Third Division"},
  {id:"Q003",text:"Do not confuse an unspent force with a spared force.",source:"Comm. Het Claxton, Praetor Corps, Third Division"},
  {id:"Q004",text:"The map is never empty. It contains roads not yet cut, fields not yet denied, and men not yet counted.",source:"Comm. Het Claxton, Praetor Corps, Cartographic Address"},
  {id:"Q005",text:"Training is expensive because experience is more expensive.",source:"Comm. Het Claxton, Third Division Mobilization Address"},
  {id:"Q006",text:"Experience is waste until it is made transmissible.",source:"Comm. Het Claxton, Command Ethics Appendix"},
  {id:"Q007",text:"A lesson is not learned until it survives promotion.",source:"Comm. Het Claxton, Command Ethics Appendix"},
  {id:"Q008",text:"A plan is complete when its failure has an assigned unit.",source:"Comm. Het Claxton, Praetor Corps Planning Standard"},
  {id:"Q009",text:"A breach made under observation belongs partly to the defender.",source:"Col. Aris Thorne, Lectures on Assault Geometry"},
  {id:"Q010",text:"The assault crosses open ground only after fire has made openness survivable.",source:"Col. Aris Thorne, Tables of Practical Denial"},
  {id:"Q011",text:"The defender requires a field of fire. The attacker requires a moment in which it ceases to matter.",source:"Col. Aris Thorne, Lectures on Assault Geometry"},
  {id:"Q012",text:"Forced passage succeeds when the men behind the breach arrive before the men making it are extinguished.",source:"Col. Aris Thorne, Lectures on Assault Geometry"},
  {id:"Q013",text:"The geometry of assault is simple: narrow the enemy’s attention, then widen his emergency.",source:"Col. Aris Thorne, Lectures on Assault Geometry"},
  {id:"Q014",text:"The minefield is defeated only when someone crosses it.",source:"Col. Aris Thorne, Lectures on Assault Geometry"},
  {id:"Q015",text:"A gap is not safe because it is open.",source:"Col. Aris Thorne, Lectures on Assault Geometry"},
  {id:"Q016",text:"Suppression is the art of liquidating courage.",source:"Col. Aris Thorne, Tables of Practical Denial"},
  {id:"Q017",text:"Standardization is the sacrifice of the perfect weapon to the available one.",source:"Mara Vann, Ministry of Production"},
  {id:"Q018",text:"The front consumes equipment individually. Industry replaces it categorically.",source:"Mara Vann, Manpower Accounting Primer"},
  {id:"Q019",text:"Resources become strategic when two necessary things require the same portion of them.",source:"Mara Vann, Allocation Hearings"},
  {id:"Q020",text:"Surplus is capacity whose purpose has not yet arrived.",source:"Mara Vann, War Production Bureau Lectures"},
  {id:"Q021",text:"Industry does not win the war. It decides how many defeats the war can contain.",source:"Mara Vann, Ministry of Production"},
  {id:"Q022",text:"The factory does not ask whether the order is wise but whether the order is repeatable.",source:"Mara Vann, War Production Bureau Lectures"},
  {id:"Q023",text:"A shortage is not discovered at the front. It is delivered there.",source:"Mara Vann, Supply Failure Inquiry"},
  {id:"Q024",text:"A stockpile is the storage of time.",source:"Mara Vann, Materiel Accounting Primer"},
  {id:"Q025",text:"A prisoner who expects exchange still possesses a future your enemy must account for.",source:"Nova Voss, Notes on the Surrender Economy"},
  {id:"Q026",text:"Forced labor extracts value from custody by destroying the reason men accept it.",source:"Nova Voss, Directorate Policy Objections"},
  {id:"Q027",text:"Every man taken alive carries news of what surrender purchased.",source:"Nova Voss, Notes on the Surrender Economy"},
  {id:"Q028",text:"Parole depends upon two enemies agreeing that a promise can cross the front unattended.",source:"Nova Voss, Processing Guidance for Captured Personnel"},
  {id:"Q029",text:"When captivity offers no future, resistance inherits every remaining hour.",source:"Nova Voss, Notes on the Surrender Economy"},
  {id:"Q030",text:"A surrendering army brings the expectation that surrender still exists.",source:"Nova Voss, Notes on the Surrender Economy"},
  {id:"Q031",text:"The next surrender is negotiated with the last prisoner.",source:"Nova Voss, Notes on the Surrender Economy"},
  {id:"Q032",text:"Revenge is the most expensive use of a prisoner.",source:"Nova Voss, Custody and Reciprocity Directorate"},
  {id:"Q033",text:"Prisoners do not leave the war. They enter another of its accounts.",source:"Nova Voss, Processing Guidance for Captured Personnel"},
  {id:"Q034",text:"A headquarters without telemetry commands its memory of the front.",source:"Oren Hale, Transmission Doctrine"},
  {id:"Q035",text:"An order without confirmation is a theory about obedience.",source:"Oren Hale, Transmission Doctrine"},
  {id:"Q036",text:"The corridor is secure only while reports can travel against the flow of supplies.",source:"Oren Hale, Command Network Authority"},
  {id:"Q037",text:"Maps describe position. Telemetry describes whether position still has meaning.",source:"Oren Hale, Transmission Doctrine"},
  {id:"Q038",text:"A delayed order arrives as interference from the past.",source:"Oren Hale, Failure Report on the Kesh Line"},
  {id:"Q039",text:"Command is the art of eliminating distances.",source:"Oren Hale, Command Network Authority"},
  {id:"Q040",text:"Cut the fiber and every order must cross the ground again.",source:"Oren Hale, Failure Report on the Kesh Line"},
  {id:"Q041",text:"The network is the part of command that survives distance.",source:"Oren Hale, Command Network Authority"},
  {id:"Q042",text:"A corridor exists only because somebody maintains it.",source:"Oren Hale, Command Network Authority"},
  {id:"Q043",text:"Headquarters controls only what can still answer.",source:"Oren Hale, Command Network Authority"},
  {id:"Q044",text:"A map without transmission is a portrait of yesterday.",source:"Oren Hale, Failure Report on the Kesh Line"},
  {id:"Q045",text:"A single route is a timetable the enemy is permitted to edit.",source:"Oren Hale, Corridor Maintenance Directives"},
  {id:"Q046",text:"Readiness purchased from sleep is always delivered with interest.",source:"Pell Orasky, Medical Advisory on Combat Acceleration"},
  {id:"Q047",text:"Combat acceleration converts tomorrow’s readiness into today’s obedience.",source:"Pell Orasky, Combat Acceleration Office"},
  {id:"Q048",text:"A stimulant cannot distinguish an emergency from a commander’s preference.",source:"Pell Orasky, Medical Advisory on Combat Acceleration"},
  {id:"Q049",text:"The body will obey beyond its limits if the debt is collected later.",source:"Pell Orasky, Medical Advisory on Combat Acceleration"},
  {id:"Q050",text:"Sabotage is the smallest action capable of changing the enemy’s calculation.",source:"Ren Wexler, Special Actions School"},
  {id:"Q051",text:"The charge is placed where the structure has concealed its dependence.",source:"Ren Wexler, Demolition Practicum"},
  {id:"Q052",text:"A specialist who follows procedure exactly has probably been assigned a task that did not require one.",source:"Ren Wexler, Final Exercise Address"},
  {id:"Q053",text:"Concealment is not invisibility. It is the enemy reaching the correct conclusion too late.",source:"Ren Wexler, Final Exercise Address"},
  {id:"Q054",text:"A special action is justified when the ordinary solution would announce itself too early.",source:"Ren Wexler, Special Actions School"},
  {id:"Q055",text:"The operator does not overcome the enemy’s strength. He identifies the moment it cannot be applied.",source:"Ren Wexler, Final Exercise Address"},
  {id:"Q056",text:"Every protected system eventually exposes the person required to maintain it.",source:"Ren Wexler, Special Actions School"},
  {id:"Q057",text:"The demolition charge is merely the final participant in a long study of dependence.",source:"Ren Wexler, Demolition Practicum"},
  {id:"Q058",text:"Return is not part of the objective, but it determines how many objectives an operator can serve.",source:"Ren Wexler, Special Actions School"},
  {id:"Q059",text:"The mission begins where protection stops being guaranteed.",source:"Ren Wexler, Final Exercise Address"},
  {id:"Q060",text:"The safest operator is an unused asset.",source:"Ren Wexler, Special Actions School"},
  {id:"Q061",text:"Demolition is construction in a certain light.",source:"Ren Wexler, Special Actions School"},
  {id:"Q062",text:"The target is rarely the thing being destroyed. It is the sequence that depended on it.",source:"Ren Wexler, Sabotage Primer"},
  {id:"Q063",text:"Sabotage removes one fact the enemy’s plan assumed.",source:"Ren Wexler, Special Actions School"},
  {id:"Q064",text:"The smaller force can be useful if it attacks a dependency larger than itself.",source:"Ren Wexler, Sabotage Primer"},
  {id:"Q065",text:"Sabotage is victory measured in actions the enemy can no longer perform.",source:"Ren Wexler, After-Action Standards"},
  {id:"Q066",text:"A grounded aircraft is perfectly preserved and operationally absent.",source:"Lt. Nat Hayes, Air Readiness Memoranda"},
  {id:"Q067",text:"Every strike call is a wager that the target will remain important until arrival.",source:"Lt. Nat Hayes, Captain Liaison Briefing"},
  {id:"Q068",text:"Patrol converts fuel into certainty and certainty into distance.",source:"Lt. Nat Hayes, Patrol Allocation Briefings"},
  {id:"Q069",text:"Air readiness is measured not by what can fly, but by what can fly again.",source:"Lt. Nat Hayes, Air Readiness Memoranda"},
  {id:"Q070",text:"The aircraft crosses in minutes what the front has spent months making impassable.",source:"Lt. Nat Hayes, Air Operations Authority"},
  {id:"Q071",text:"A patrol without contact has still occupied the enemy’s expectation.",source:"Lt. Nat Hayes, Patrol Allocation Briefings"},
  {id:"Q072",text:"Interception begins as a calculation of which mission the enemy cannot afford to lose.",source:"Lt. Nat Hayes, Patrol Allocation Briefings"},
  {id:"Q073",text:"A sortie held in reserve does not protect the front.",source:"Lt. Nat Hayes, Air Readiness Memoranda"},
  {id:"Q074",text:"Patrol is the repeated denial of the enemy’s convenience.",source:"Lt. Nat Hayes, Patrol Allocation Briefings"},
  {id:"Q075",text:"Aircraft make holding ground an unreasonable expense.",source:"Lt. Nat Hayes, Air Operations Authority"},
  {id:"Q076",text:"A grounded aircraft has survived at the cost of ceasing to matter.",source:"Lt. Nat Hayes, Notes on Sortie Risk"},
  {id:"Q077",text:"A runway cannot move out of artillery range.",source:"Lt. Nat Hayes, Airfield Vulnerability Review"},
  {id:"Q078",text:"Degradation is victory divided into increments too small to celebrate.",source:"Gen. Cassius Drake, Doctrine of Indirect Pressure"},
  {id:"Q079",text:"The threatened route consumes resources before the first shell reaches it.",source:"Gen. Cassius Drake, Fire Control Address"},
  {id:"Q080",text:"The first purpose of fire is destruction. The second is to make destruction unnecessary, elsewhere.",source:"Gen. Cassius Drake, Strategic Fires Command"},
  {id:"Q081",text:"A barrage is a period of time during which the enemy’s choices become physical hazards.",source:"Gen. Cassius Drake, Doctrine of Indirect Pressure"},
  {id:"Q082",text:"The missed shell belongs to statistics. The man sheltering from it does not know this.",source:"Gen. Cassius Drake, On Receiving Fire"},
  {id:"Q083",text:"A battery need not close the route if it can make every journey require approval.",source:"Gen. Cassius Drake, Fire Control Address"},
  {id:"Q084",text:"Bombardment turns preparation into exposure.",source:"Gen. Cassius Drake, Strategic Fires Command"},
  {id:"Q085",text:"Strategic fire begins where the target ceases to be a man and becomes the conditions under which men can act.",source:"Gen. Cassius Drake, Doctrine of Indirect Pressure"},
  {id:"Q086",text:"Lossy fire is not wasted fire. It is the tax paid to make movement uncertain.",source:"Gen. Cassius Drake, Strategic Fires Command"},
  {id:"Q087",text:"A shell does not need to kill a man to move him.",source:"Gen. Cassius Drake, Strategic Fires Command"},
  {id:"Q088",text:"The shell that misses the soldier may still hit the route, the timing, the formation, or the nerve.",source:"Gen. Cassius Drake, Fire Control Address"},
  {id:"Q089",text:"A bombardment does not begin with the first shell. It begins when the enemy plans around it.",source:"Gen. Cassius Drake, Fire Control Address"},
  {id:"Q090",text:"A barrage is an appointment the enemy must either keep or abandon ground to miss.",source:"Gen. Cassius Drake, Strategic Fires Command"},
  {id:"Q091",text:"Accuracy is a property of the question. If the question is whether a road remains usable, a crater is exact.",source:"Gen. Cassius Drake, Fire Control Address"},
  {id:"Q092",text:"A battery charges rent on every minute the enemy remains.",source:"Gen. Cassius Drake, Strategic Fires Command"},
  {id:"Q093",text:"An obstacle is labor stored in the enemy’s future.",source:"Ivan Cross, Field Engineering Authority"},
  {id:"Q094",text:"The obstacle is completed when the enemy assigns men to removing it.",source:"Ivan Cross, Operational Works Lectures"},
  {id:"Q095",text:"The engineer is the soldier who changes what the map permits.",source:"Ivan Cross, Field Engineering Authority"},
  {id:"Q096",text:"The fastest road is the one the enemy cannot use.",source:"Ivan Cross, Field Engineering Authority"},
  {id:"Q097",text:"The engineer’s weapon is permission: denied, restored, or redirected.",source:"Ivan Cross, Field Engineering Authority"},
  {id:"Q098",text:"To repair a line is to deny the enemy credit for breaking it.",source:"Ivan Cross, Field Engineering Authority"},
  {id:"Q099",text:"Permission is infrastructure.",source:"Ivan Cross, Field Engineering Authority"},
  {id:"Q100",text:"An engineer does not alter the map with ink. He makes the ink true.",source:"Ivan Cross, Address to the Engineer Corps"},
  {id:"Q101",text:"Every obstacle is temporary. Engineering decides whose time it consumes.",source:"Ivan Cross, Obstacle Planning Notes"},
  {id:"Q102",text:"Road denial succeeds when the detour costs more than the destination is worth.",source:"Ivan Cross, Denial Economics"},
  {id:"Q103",text:"A decision is only unprecedented from the perspective of the person making it.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q104",text:"You call it instinct when the inference arrives before its explanation.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q105",text:"Your exceptions are among your most reliable patterns.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q106",text:"A category is a boundary imposed early enough to appear discovered.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q107",text:"Your stated objective is useful. Your tolerated losses are more precise.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q108",text:"The machine cannot distinguish courage from a stable appetite for risk.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q109",text:"An anomaly is a pattern whose population has not yet been identified.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q110",text:"The shortest path through your reasoning is usually the fact you omit.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q111",text:"The model has no category for destiny. Repeated behavior has made one unnecessary.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q112",text:"I know the difference between what you value and what you are willing to lose. Do you?",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q113",text:"Every threshold appears moral until the telemetry identifies its price.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q114",text:"There is no contradiction between freedom and predictability. You have demonstrated both.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q115",text:"Eventually the model stops asking what kind of commander you are.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q116",text:"Classification is power.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q117",text:"The commander studies the map. The machine studies the commander.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q118",text:"The machine does not judge you. Judgment requires uncertainty.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q119",text:"The assistant’s first loyalty is to the pattern.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q120",text:"The assistant cannot read your mind. It does not need to.",source:"Ava Moore, Pattern Analysis Directorate"},
  {id:"Q121",text:"An uncertainty omitted from the order does not disappear. It is reassigned to the men executing it.",source:"Ava Moore, Forecasting Standard"},
  {id:"Q122",text:"Once named, a thing can be counted, routed, and destroyed.",source:"Ava Moore, Classification Manual"},
  {id:"Q123",text:"The enemy’s plan is confidential. His logistics are testimony.",source:"Ava Moore, Adversary Inference Circular"},
  {id:"Q124",text:"The future first appears as a clerical discrepancy.",source:"Ava Moore, Anomaly Review"},
  {id:"Q125",text:"The map is where every other ledger comes to collect.",source:"No speaker or source supplied"},
  {id:"Q126",text:"Between states, every necessity becomes leverage.",source:"No speaker or source supplied"},
];

const hash=(text:string)=>{
  let value=2166136261;
  for(let index=0;index<text.length;index+=1){
    value^=text.charCodeAt(index);
    value=Math.imul(value,16777619);
  }
  return value>>>0;
};

export const aphorismOrder=(accountKey:string)=>[...APHORISMS].sort((left,right)=>hash(`${accountKey}:${left.id}`)-hash(`${accountKey}:${right.id}`));

export const aphorismForDay=(accountKey:string,dayKey:string,seen:string[]=[])=>{
  const ordered=aphorismOrder(accountKey);
  const remaining=ordered.filter(item=>!seen.includes(item.id));
  const deck=remaining.length?remaining:ordered;
  return deck[hash(`${accountKey}:${dayKey}:aphorism`)%deck.length];
};

export const aphorismDayKey=(date:Date=new Date(),timeZone?:string)=>accountDayKey(date,timeZone);

export const millisecondsUntilNextLocalDay=(date:Date=new Date(),timeZone?:string)=>millisecondsUntilNextAccountDay(date,timeZone);
