import type { CampaignEvent } from "./game";

// Authored campaign conditions. These are not wording skins: each entry carries
// its own state modifiers and resolution report.
export const ADDITIONAL_CAMPAIGN_EVENTS: CampaignEvent[] = [
  {id:"maps-arrive-wet",label:"The Maps Arrive Wet",category:"COMMAND FRICTION",phases:["contact"],brief:"The divisional map issue crossed the river in an open truck. Ink has migrated farther than the reconnaissance line.",report:"Damaged maps degraded execution and let the enemy exploit the confusion.",quote:"A map need not be false to become an enemy document.",exact:["Execution Confidence -6%","Enemy front pressure +0.12 km"],risk:["Improvised grid references may survive into tomorrow's fire plan"],modifiers:{confidence:-.06,enemyPressure:.12}},
  {id:"orchard-listening-post",label:"The Orchard Listening Post",category:"RECONNAISSANCE",phases:["contact"],brief:"A patrol remained beyond the orchard after the line withdrew and has counted every vehicle entering the enemy assembly area.",report:"The isolated post improved classification and reduced loss exposure.",quote:"Sometimes the best observation post is the one the map has already surrendered.",exact:["Execution Confidence +4%","Friendly casualty factor ×0.96"],risk:["The patrol may be cut off after resolution"],modifiers:{confidence:.04,casualty:.96}},
  {id:"airstrip-lanterns",label:"Lanterns on the Emergency Strip",category:"AIR OPERATIONS",phases:["contact"],brief:"Ground crews have marked a farm strip by hand. Aircraft can operate there, but every approach advertises the field to enemy reconnaissance.",report:"Forward aviation improved pressure and execution while exposed servicing increased losses.",quote:"An airfield is a promise made to every observer in range.",exact:["Execution Confidence +2%","Friendly front pressure +0.08 km","Combat casualty factor ×1.08"],risk:["The strip may draw fires into the surrounding farms"],modifiers:{confidence:.02,friendlyPressure:.08,casualty:1.08}},
  {id:"captured-switchboard",label:"The Captured Switchboard Still Rings",category:"SIGNALS",phases:["contact"],brief:"Enemy callers continue to use a municipal exchange abandoned during the retreat. Linguists and artillery observers are sharing one headset.",report:"Live traffic improved supply allocation, though exploiting the exchange increased movement demand.",quote:"A telephone becomes intelligence when the wrong army answers.",exact:["Supply use ×1.14","Industrial output ×0.95"],risk:["Answering too cleverly will disclose the compromise"],modifiers:{supplyUse:1.14,productionOutput:.95}},

  {id:"traffic-control-shot",label:"Traffic Control Is Shot at the Crossroads",category:"MOVEMENT",phases:["compression"],brief:"The road remains open. The men who knew where every column belonged do not.",report:"Emergency priority control improved throughput while civil distribution absorbed the delay.",quote:"A road jam is an order of battle written bumper to bumper.",exact:["Industrial output ×1.04","Supply use ×0.92","Resistance +0.4 at resolution"],risk:["Rear formations may arrive before their ammunition"],modifiers:{productionOutput:1.04,supplyUse:.92,resistance:.4}},
  {id:"barrage-walks-away",label:"The Barrage Walks Away",category:"FIRE SUPPORT",phases:["compression"],brief:"The assault companies lost the timetable in smoke. The guns continue advancing their fires exactly as ordered.",report:"Reconstructed fire traffic improved execution and restored part of the supply chain.",quote:"Perfect artillery preparation can abandon imperfect infantry.",exact:["Execution Confidence +6%","Supply conversion ×1.05"],risk:["Stopping the schedule may expose the assault to unplanned fires"],modifiers:{confidence:.06,supplyConversion:1.05}},
  {id:"bridge-load-dispute",label:"The Bridge Has Two Load Tables",category:"ENGINEERING",phases:["compression"],brief:"The engineers and the armored staff possess different limits for the same temporary bridge. Both tables carry official seals.",report:"The disputed crossing imposed pressure and raised battlefield loss exposure.",quote:"A bridge fails first in the paperwork, then all at once.",exact:["Enemy front pressure +0.28 km","Combat casualty factor ×1.06"],risk:["Armor concentration remains delayed"],modifiers:{enemyPressure:.28,casualty:1.06}},
  {id:"quarry-machine-guns",label:"Machine Guns Remain in the Quarry",category:"ENEMY POSITION",phases:["compression"],brief:"Aerial photographs marked the quarry cleared. Infantry reports fire from three benches and a conveyor tunnel.",report:"Additional planning improved execution while the surviving position surrendered time.",quote:"A photograph records the surface. A defender lives underneath it.",exact:["Execution Confidence +8%","Friendly front pressure -0.15 km"],risk:["A second attack may repeat the first one's geometry"],modifiers:{confidence:.08,friendlyPressure:-.15}},

  {id:"boots-before-rifles",label:"The Boots Arrive Before the Rifles",category:"REPLACEMENTS",phases:["exhaustion"],brief:"Replacement drafts have reached the railhead. Their personal weapons remain three junctions east under a different priority code.",report:"The stalled draft increased flight pressure and entered the legitimacy ledger.",quote:"A reinforcement without its weapon is only another ration claim.",exact:["Desertion flow ×1.30","Legitimacy -0.8 at resolution"],risk:["Pressure to issue captured weapons may damage training coherence"],modifiers:{desertion:1.3,legitimacy:-.8}},
  {id:"hospital-train-missing",label:"The Hospital Train Is Missing",category:"MEDICAL LOGISTICS",phases:["exhaustion"],brief:"A marked train left the forward siding and has not reported at any western junction. Evacuation now competes with ammunition traffic.",report:"Medical congestion reduced output and deepened maintenance debt.",quote:"A casualty becomes politics when transport stops.",exact:["Industrial output ×0.82","Maintenance debt +3 at resolution"],risk:["Rumor will reach the cities before the train does"],modifiers:{productionOutput:.82,maintenance:3}},
  {id:"battery-tubes-condemned",label:"The Battery Condemns Its Own Tubes",category:"ARTILLERY",phases:["exhaustion"],brief:"Gun crews have exceeded the certified life of every tube in the battalion. The fire plan assumes they remain interchangeable with new steel.",report:"Restricted firing reduced losses while raising flight pressure among exposed crews.",quote:"A worn gun can obey one more order. It cannot promise where the shell will land.",exact:["Combat casualty factor ×0.97","Desertion flow ×1.12","Legitimacy +0.4 at resolution"],risk:["Emergency firing may consume the remaining safe life"],modifiers:{casualty:.97,desertion:1.12,legitimacy:.4}},
  {id:"veterans-teach-trench",label:"Veterans Teach the Trench",category:"FIELD ADAPTATION",phases:["exhaustion"],brief:"Survivors from three depleted companies are training replacements in the line because no rear school can reproduce the present war.",report:"Field adaptation reduced supply use while increasing domestic strain.",quote:"The shortest syllabus is a veteran pointing at the place his friend died.",exact:["Supply use ×0.90","Resistance +1.2 at resolution","Legitimacy -0.5 at resolution"],risk:["Cadre losses cannot be replaced by the lesson they taught"],modifiers:{supplyUse:.9,resistance:1.2,legitimacy:-.5}},

  {id:"city-water-stops",label:"The Ruined City Loses Water",category:"URBAN SUSTAINMENT",phases:["terminal"],brief:"Pumps have failed across the forward districts. Troops, civilians, workshops, and hospitals now draw from the same tanker column.",report:"The emergency water reserve increased pressure and confidence at exceptional exposure.",quote:"A city becomes terrain when its pipes stop being civil.",exact:["Friendly front pressure +0.35 km","Execution Confidence +5%","Combat casualty factor ×1.22"],risk:["Disease may become an operational factor"],modifiers:{friendlyPressure:.35,confidence:.05,casualty:1.22}},
  {id:"tank-recovery-square",label:"A Tank Burns in the Recovery Square",category:"ARMORED OPERATIONS",phases:["terminal"],brief:"A disabled tank blocks the only protected recovery route. Enemy observers have registered every vehicle sent toward it.",report:"The exposed recovery degraded execution and surrendered additional pressure.",quote:"A wreck becomes a fortification for whichever side controls the tow cable.",exact:["Execution Confidence -8%","Enemy front pressure +0.15 km"],risk:["Another recovery vehicle may join the obstruction"],modifiers:{confidence:-.08,enemyPressure:.15}},
  {id:"drone-spectrum-crowded",label:"The Drone Spectrum Becomes a Crowd",category:"UNCREWED SYSTEMS",phases:["terminal"],brief:"Friendly and enemy control links occupy the same bands. Operators are flying by habit through interference neither side fully understands.",report:"Spectrum congestion degraded supply conversion and increased consumption.",quote:"A sky full of machines can still be blind.",exact:["Supply conversion ×0.82","Supply use ×1.15","Friendly front pressure -0.10 km"],risk:["Authentication mistakes may turn friendly relay into enemy access"],modifiers:{supplyConversion:.82,supplyUse:1.15,friendlyPressure:-.1}},
  {id:"river-rises-behind",label:"The River Rises Behind the Batteries",category:"RIVER OPERATIONS",phases:["terminal"],brief:"Upstream rain has reached the gun positions before the forecast. Ammunition stacks stand on planks; the withdrawal road is already soft.",report:"Rising water preceded increased enemy pressure and friendly losses.",quote:"A river attacks the rear without crossing the front.",exact:["Enemy front pressure +0.30 km","Combat casualty factor ×1.08"],risk:["Heavy batteries may become fixed positions by morning"],modifiers:{enemyPressure:.3,casualty:1.08}},
  {id:"snipers-in-bell-tower",label:"The Bell Tower Has Three Snipers",category:"URBAN COMBAT",phases:["terminal"],brief:"Three firing patterns indicate three teams in one shattered tower. Every direct approach is visible; every indirect shot risks the aid station below.",report:"The emergency assault increased pressure and confidence at exceptional exposure.",quote:"One high room can govern an entire street.",exact:["Friendly front pressure +0.35 km","Execution Confidence +5%","Combat casualty factor ×1.22"],risk:["Destroying the tower may cost legitimacy"],modifiers:{friendlyPressure:.35,confidence:.05,casualty:1.22}},
  {id:"rear-guard-radio",label:"The Rear Guard Answers on a Civil Set",category:"COMMAND SURVIVAL",phases:["terminal"],brief:"The rear guard's military net is gone. A municipal transmitter now carries orders, casualty lists, and requests for fire in the clear.",report:"Improvised command degraded execution and exposed the plan to enemy pressure.",quote:"An insecure order can still arrive in time.",exact:["Execution Confidence -8%","Enemy front pressure +0.15 km"],risk:["Enemy traffic analysis will retain the entire sequence"],modifiers:{confidence:-.08,enemyPressure:.15}},
  {id:"causeway-sinks",label:"The Causeway Sinks Under the Supply Column",category:"LOGISTICS",phases:["terminal"],brief:"Repeated heavy traffic has pushed the temporary road below the waterline. The front still exists; its wheeled connection now has tides.",report:"Causeway failure reduced supply conversion and increased transport demand.",quote:"A road becomes a bridge one inch of water at a time.",exact:["Supply conversion ×0.82","Supply use ×1.15","Friendly front pressure -0.10 km"],risk:["Recovery vehicles may close the remaining lane"],modifiers:{supplyConversion:.82,supplyUse:1.15,friendlyPressure:-.1}},
  {id:"enemy-stretcher-drill",label:"Enemy Stretcher Drills Begin Before Dawn",category:"ENEMY INTENT",phases:["terminal"],brief:"Observers report organized casualty drills behind the enemy line. The preparation is too large for routine defense and too calm for panic.",report:"Forward medical preparation preceded increased enemy pressure and friendly losses.",quote:"An army rehearses its losses when it has already selected the attack.",exact:["Enemy front pressure +0.30 km","Combat casualty factor ×1.08"],risk:["Prepared casualty capacity permits a longer offensive"],modifiers:{enemyPressure:.3,casualty:1.08}},
];

export const CAMPAIGN_EVENT_CALCULUS: Record<string,string> = {
  "maps-arrive-wet":"phantom-reserve",
  "orchard-listening-post":"surveyors-dawn",
  "airstrip-lanterns":"open-sky",
  "captured-switchboard":"first-rail-cut",
  "traffic-control-shot":"junction-priority",
  "barrage-walks-away":"relay-harvest",
  "bridge-load-dispute":"relief-column",
  "quarry-machine-guns":"staff-conference",
  "boots-before-rifles":"replacement-refusal",
  "hospital-train-missing":"bearing-sequence",
  "battery-tubes-condemned":"burial-details",
  "veterans-teach-trench":"ration-script",
  "city-water-stops":"national-reserve",
  "tank-recovery-square":"archive-fires",
  "drone-spectrum-crowded":"last-bridge",
  "river-rises-behind":"hospitals-west",
  "snipers-in-bell-tower":"national-reserve",
  "rear-guard-radio":"archive-fires",
  "causeway-sinks":"last-bridge",
  "enemy-stretcher-drill":"hospitals-west",
};
