const CAMPAIGN_NAMES = [
  "ACHILLES",
  "ADONIS",
  "AJAX",
  "ANDROMACHE",
  "ANTIGONE",
  "APOLLO",
  "ARIEL",
  "ARTEMIS",
  "ATHENA",
  "ATLAS",
  "BANQUO",
  "BEATRICE",
  "BEOWULF",
  "BELLEROPHON",
  "BRUTUS",
  "CALIBAN",
  "CASSANDRA",
  "CERBERUS",
  "CIRCE",
  "CLAUDIUS",
  "CORDELIA",
  "CRESSIDA",
  "CYMBELINE",
  "DAEDALUS",
  "DEMETRIUS",
  "DESDEMONA",
  "DIOMEDES",
  "DIONYSUS",
  "ELECTRA",
  "ENDYMION",
  "ENKIDU",
  "ERIS",
  "FALSTAFF",
  "FORTINBRAS",
  "GANYMEDE",
  "GERTRUDE",
  "GILGAMESH",
  "GONERIL",
  "GRENDEL",
  "HAMLET",
  "HECATE",
  "HECTOR",
  "HELEN",
  "HELIOS",
  "HEPHAESTUS",
  "HERMES",
  "HERMAPHRODITUS",
  "HORATIO",
  "HYPERION",
  "ICARUS",
  "IMOGEN",
  "ISHTAR",
  "JANUS",
  "JULIET",
  "KINGLEAR",
  "LAERTES",
  "LAVINIA",
  "LEONTES",
  "LUCIFER",
  "MACBETH",
  "MACDUFF",
  "MEDUSA",
  "MERCUTIO",
  "MERLIN",
  "MINERVA",
  "MIRANDA",
  "MORRIGAN",
  "NARCISSUS",
  "NEMESIS",
  "OBERON",
  "ODIN",
  "ODYSSEUS",
  "OPHELIA",
  "ORESTES",
  "ORLANDO",
  "ORPHEUS",
  "OSRIC",
  "OTHELLO",
  "PANDORA",
  "PATROCLUS",
  "PENTHESILEA",
  "PERSEPHONE",
  "PERSEUS",
  "PORTIA",
  "POSEIDON",
  "PRIAM",
  "PROSPERO",
  "PUCK",
  "REGAN",
  "ROMEO",
  "ROSALIND",
  "SCYLLA",
  "SET",
  "SIEGFRIED",
  "SISYPHUS",
  "TAMORA",
  "TEMPEST",
  "THESEUS",
  "THOR",
  "TITANIA",
  "TRINCULO",
  "TYBALT",
  "ULYSSES",
  "VIOLA",
  "VOLTAIRE",
  "WOTAN",
  "ZEUS",
] as const;

const mix = (value: number) => {
  let mixed = Math.abs(Math.trunc(value)) >>> 0;
  mixed = Math.imul(mixed ^ (mixed >>> 16), 0x45d9f3b) >>> 0;
  mixed = Math.imul(mixed ^ (mixed >>> 16), 0x45d9f3b) >>> 0;
  return (mixed ^ (mixed >>> 16)) >>> 0;
};

export const campaignSeedId = (seed: number) => {
  const mixed = mix(seed);
  const name = CAMPAIGN_NAMES[mixed % CAMPAIGN_NAMES.length];
  const checksum = mix(mixed ^ 0x9e3779b9) % 10_000;
  return `#WAR-${name}-${String(checksum).padStart(4, "0")}`;
};

export const CAMPAIGN_SEED_NAME_COUNT = CAMPAIGN_NAMES.length;
