import { GameState, Resource, coverage, estimateDay, fmt, projectForceGeneration, projectProduction } from "./game";

export type SemanticTag = "ACTION"|"INSPECT"|"CONCEPT"|"MODULE_LINK"|"STATUS"|"ATMOSPHERE"|"STRUCTURE";
export type Concept = { id:string; label:string; definition:string; normal?:string; consequence:string; control?:{label:string;family?:string;module:string}; related:string[] };
export type CalculationRow = { label:string; value:string; concept?:string; tone?:"loss"|"gain"|"neutral" };
export type Calculation = { title:string; equation:string; basis:string; rows:CalculationRow[]; result:string; uncertainties?:string[] };

export const CONCEPTS:Record<string,Concept> = {
  "industrial-health":{id:"industrial-health",label:"Industrial Health",definition:"Factory uptime, maintenance condition, rail throughput, and accumulated repair debt.",normal:"70–85%",consequence:"Multiplies daily output on every production line.",control:{label:"Organize Industry",family:"industry",module:"national"},related:["materiel-condition","production-target","production-coverage"]},
  "production-target":{id:"production-target",label:"Production Target",definition:"The allocation policy deciding which production line receives preferential industrial capacity.",normal:"Balanced is 25% per line",consequence:"A focused line receives 46% allocation and a specialization output bonus; other lines fall to 18%.",control:{label:"Set Production Target",family:"production",module:"national"},related:["industrial-health","munitions","production-coverage"]},
  "production-coverage":{id:"production-coverage",label:"Days of Coverage",definition:"How many days the current stock can sustain the current daily use rate.",normal:"5+ days stable // below 2 days critical",consequence:"Short lines penalize Readiness, Equipment, Materiel, and battlefield conversion.",control:{label:"Set Production Target",family:"production",module:"national"},related:["munitions","operational-tempo","industrial-health"]},
  "lines-below-two-days":{id:"lines-below-two-days",label:"Lines Below Two Days",definition:"Count of production lines whose stock is less than twice their current daily use.",normal:"0",consequence:"Each shortage contributes to daily degradation and reduces maneuver confidence.",control:{label:"Set Production Target",family:"production",module:"national"},related:["production-coverage","industrial-health","readiness"]},
  "munitions":{id:"munitions",label:"Munitions",definition:"Current usable shell, rocket, missile, and ammunition stock available to the operational system.",normal:"5+ days of coverage",consequence:"Low stock increases casualties and constrains tempo and maneuver selection.",control:{label:"Set Production Target",family:"production",module:"national"},related:["production-coverage","industrial-health","operational-tempo"]},
  "maintenance-debt":{id:"maintenance-debt",label:"Maintenance Debt",definition:"Accumulated deferred repair, bearing wear, tooling damage, and transport fatigue carried by the industrial system.",normal:"0–30",consequence:"Reduces the Production circuit condition factor. Overtime and retooling increase it; maintenance posture reduces it.",control:{label:"Organize Industry",family:"industry",module:"national"},related:["industrial-health","production-target","production-coverage"]},
  "workforce-factor":{id:"workforce-factor",label:"Workforce Factor",definition:"Available civilian workforce divided by the campaign industrial baseline, clamped to the circuit operating range.",normal:"90–104%",consequence:"Multiplies output on every production line before specialization and policy effects.",control:{label:"Define Service Obligation",family:"service",module:"military"},related:["industrial-health","training-queue","production-target"]},
  "retooling-loss":{id:"retooling-loss",label:"Retooling Loss",definition:"One-resolution conversion penalty applied when industrial allocation changes target.",normal:"0% while stable",consequence:"Changing target cuts all line output by 28% for the conversion day before the new allocation takes effect.",control:{label:"Set Production Target",family:"production",module:"national"},related:["production-target","maintenance-debt","production-coverage"]},
  "training-queue":{id:"training-queue",label:"Training Queue",definition:"Recruits waiting for admission into a training cohort. They are not yet soldiers.",normal:"0.5–1.5 capacity-days",consequence:"A large queue delays the conversion of enlistment into Armed Forces.",control:{label:"Provision Training Capacity",family:"training-capacity",module:"military"},related:["training-capacity","training-duration","graduates"]},
  "training-capacity":{id:"training-capacity",label:"Training Capacity",definition:"Maximum recruits that can be admitted to training each day.",consequence:"Capacity above intake contracts backlog; capacity below intake expands it.",control:{label:"Provision Training Capacity",family:"training-capacity",module:"military"},related:["training-queue","graduates"]},
  "training-cohort":{id:"training-cohort",label:"Training Cohort",definition:"A dated body of admitted recruits moving through the current training standard together.",normal:"At least one cohort graduating before replacement demand peaks",consequence:"A cohort adds no soldiers until its remaining training days reach zero; admission-day quality determines effective graduates.",control:{label:"Set Training Standard",family:"training-standard",module:"military"},related:["training-capacity","graduates","training-queue"]},
  "graduates":{id:"graduates",label:"Effective Graduates",definition:"Quality-adjusted members of matured training cohorts added to Armed Forces at resolution.",consequence:"Graduates must still receive equipment and pass the readiness gate before joining Deployable Force.",control:{label:"Set Training Standard",family:"training-standard",module:"military"},related:["training-cohort","equipment-assignment","deployable-force"]},
  "equipment-assignment":{id:"equipment-assignment",label:"Equipment Assignment",definition:"The issue of serviceable weapons, vehicles, radios, and support equipment to effective graduates.",normal:"75–90% of graduates assigned",consequence:"Unequipped graduates enter Reserve instead of Deployable Force; low Equipment Coverage constrains assignment.",control:{label:"Secure External Supply",family:"supply",module:"diplomacy"},related:["graduates","equipment-coverage","deployable-force"]},
  "readiness":{id:"readiness",label:"Readiness",definition:"Share of the field force presently able to execute its assigned mission.",normal:"65–85%",consequence:"Multiplies Deployable Force when Effective Force is calculated.",control:{label:"Set Operational Tempo",family:"tempo",module:"military"},related:["deployable-force","equipment-coverage","operational-tempo"]},
  "equipment-coverage":{id:"equipment-coverage",label:"Equipment Coverage",definition:"Share of field formations with serviceable assigned weapons, vehicles, radios, and support equipment.",normal:"75–90%",consequence:"Multiplies Deployable Force in Effective Force.",control:{label:"Secure External Supply",family:"supply",module:"diplomacy"},related:["readiness","deployable-force","industrial-health"]},
  "deployable-force":{id:"deployable-force",label:"Deployable Force",definition:"Trained armed personnel currently available for frontline employment.",consequence:"Reduced by casualties, net desertion, and rear-area commitments.",control:{label:"Define Service Obligation",family:"service",module:"military"},related:["readiness","equipment-coverage","training-queue"]},
  "operational-tempo":{id:"operational-tempo",label:"Operational Tempo",definition:"Standing exchange rate between supply, casualties, and battlefield pressure.",consequence:"Changes daily casualty, supply-use, and front-pressure multipliers.",control:{label:"Set Operational Tempo",family:"tempo",module:"military"},related:["munitions","readiness","pressure"]},
};

export const calculationFor=(metric:string,s:GameState):Calculation=>{
  const e=estimateDay(s);
  if(metric==="materiel") {const p=projectProduction(s),m=p.lines.find(x=>x.resource==="munitions")!;return {title:"Production Circuit at Day Resolution",equation:"stock + (base output × allocation × workforce × condition × policy × specialization × retooling) − operational use",basis:"PROJECTED // CURRENT POLICIES AND ORDERS",rows:[{label:"OPENING MUNITIONS",value:fmt(m.opening,true),concept:"munitions"},{label:"CIRCUIT OUTPUT",value:`+${fmt(m.output,true)}`,concept:"industrial-health",tone:"gain"},{label:"OPERATIONAL USE",value:`−${fmt(m.use,true)}`,concept:"operational-tempo",tone:"loss"},{label:"WORKFORCE FACTOR",value:`${Math.round(p.workforceFactor*100)}%`,concept:"workforce-factor"},{label:"CONDITION FACTOR",value:`${Math.round(p.conditionFactor*100)}%`,concept:"industrial-health"},{label:"MAINTENANCE DEBT",value:`${p.maintenanceDebtAfter.toFixed(0)} / 100`,concept:"maintenance-debt"},{label:"PRODUCTION TARGET",value:p.target.toUpperCase(),concept:"production-target"},{label:"RETOOLING",value:p.retooled?"−28% TODAY":"NONE",concept:"retooling-loss"},...p.lines.map(line=>({label:`${line.resource.toUpperCase()} COVERAGE`,value:`${line.coverage.toFixed(1)} DAYS`,concept:"production-coverage",tone:line.status==="critical"?"loss" as const:"neutral" as const}))],result:`${fmt(m.closing,true)} PROJECTED MUNITIONS // ${p.shortages} CRITICAL LINES`};}
  if(metric==="training") {const f=projectForceGeneration(s);return{title:"Force Generation Circuit",equation:"intake → queue → dated cohort → quality graduation → equipment assignment → reserve or deployable formation",basis:"PROJECTED // NEXT RESOLUTION",rows:[{label:"OPENING QUEUE",value:fmt(f.queueOpening,true),concept:"training-queue"},{label:"DAILY INTAKE",value:`+${fmt(f.grossIntake,true)}`,concept:"training-queue",tone:"gain"},{label:"ADMITTED TODAY",value:fmt(f.admitted,true),concept:"training-capacity"},{label:"ACTIVE COHORTS",value:String(f.cohortsClosing),concept:"training-cohort"},{label:"EFFECTIVE GRADUATES",value:fmt(f.effectiveGraduates,true),concept:"graduates",tone:"gain"},{label:"EQUIPMENT ASSIGNED",value:fmt(f.equipmentAssigned,true),concept:"equipment-assignment"},{label:"RESERVE RELEASED",value:fmt(f.reserveReleased,true),concept:"deployable-force",tone:"gain"},{label:"DEPLOYABLE ASSIGNED",value:`+${fmt(f.deployableAssigned,true)}`,concept:"deployable-force",tone:"gain"}],result:`${fmt(f.deployableClosing,true)} PROJECTED DEPLOYABLE FORCE`};}
  if(metric==="armed") return{title:"Effective Force",equation:"deployable force × readiness × equipment coverage",basis:"LIVE // CURRENT DAY",rows:[{label:"DEPLOYABLE FORCE",value:fmt(s.deployable,true),concept:"deployable-force"},{label:"READINESS",value:`× ${(s.readiness/100).toFixed(2)}`,concept:"readiness"},{label:"EQUIPMENT COVERAGE",value:`× ${(s.equipment/100).toFixed(2)}`,concept:"equipment-coverage"}],result:`${fmt(s.deployable*s.readiness/100*s.equipment/100,true)} EFFECTIVE FORCE`};
  if(metric==="readiness") return{title:"Readiness State",equation:"prior readiness + replacement effect − shortages − tempo debt",basis:"AUTHORITATIVE STATE // DAILY MODIFIERS",rows:[{label:"CURRENT READINESS",value:`${s.readiness.toFixed(1)}%`,concept:"readiness"},{label:"TRAINING QUALITY",value:`${s.quality.toFixed(0)}%`,concept:"training-capacity"},{label:"OPERATIONAL TEMPO",value:s.tempo.toUpperCase(),concept:"operational-tempo"},{label:"CRITICAL LINES",value:String(Object.keys(s.production).filter(k=>coverage(s,k as Resource)<2).length),concept:"lines-below-two-days"}],result:`${s.readiness.toFixed(1)}% CURRENT READINESS`};
  if(metric==="population") return{title:"Population and Labor Base",equation:"population − recorded war deaths // workforce − military intake",basis:"AUTHORITATIVE STATE",rows:[{label:"OPENING POPULATION",value:"18,420,000"},{label:"CURRENT POPULATION",value:fmt(s.population,true)},{label:"RECORDED WAR DEATHS",value:fmt(18420000-s.population,true),tone:"loss"},{label:"WORKFORCE",value:fmt(s.workforce,true)}],result:`${fmt(s.population,true)} LIVING POPULATION`};
  if(metric==="enlistment") return{title:"Daily Recruitment Intake",equation:"voluntary intake + forced intake → training queue",basis:"DAILY RATE // CURRENT POLICIES",rows:[{label:"VOLUNTARY",value:`+${fmt(s.voluntary,true)}`},{label:"FORCED",value:`+${fmt(s.forced,true)}`},{label:"TRAINING QUEUE",value:fmt(s.queue,true),concept:"training-queue"},{label:"TRAINING CAPACITY",value:fmt(s.training,true),concept:"training-capacity"}],result:`${fmt(s.voluntary+s.forced,true)} RECRUITS PER DAY`};
  if(metric==="equipment") return{title:"Equipment Coverage",equation:"serviceable assigned equipment ÷ required formation equipment",basis:"AUTHORITATIVE STATE",rows:[{label:"CURRENT COVERAGE",value:`${s.equipment.toFixed(1)}%`,concept:"equipment-coverage"},{label:"ARMOR STOCK",value:fmt(s.production.armor.stock,true)},{label:"FLIGHT STOCK",value:fmt(s.production.flight.stock,true)},{label:"INDUSTRIAL HEALTH",value:`${s.materiel.toFixed(1)}%`,concept:"industrial-health"}],result:`${s.equipment.toFixed(1)}% FORMATIONS EQUIPPED`};
  if(metric==="treasury") return{title:"Daily Treasury Position",equation:"current treasury + baseline revenue − armed-force burden − active policy costs",basis:"PROJECTED // DAILY RESOLUTION",rows:[{label:"CURRENT TREASURY",value:`${s.treasury.toFixed(1)} B`},{label:"BASELINE REVENUE",value:"+3.4 B",tone:"gain"},{label:"ARMED-FORCE BURDEN",value:`−${(s.armed/185000).toFixed(1)} B`,tone:"loss"}],result:`${(s.treasury+3.4-s.armed/185000).toFixed(1)} B BEFORE POLICY COSTS`};
  if(metric==="legitimacy") return{title:"Political Tolerance",equation:"prior legitimacy + policy effects − casualty burden − atrocity exposure",basis:"AUTHORITATIVE STATE // PROJECTED PRESSURES",rows:[{label:"CURRENT LEGITIMACY",value:`${s.legitimacy.toFixed(1)}%`},{label:"RESISTANCE",value:`${s.resistance.toFixed(1)}%`},{label:"ATROCITY EXPOSURE",value:`${s.atrocityExposure.toFixed(1)}%`},{label:"PROJECTED CASUALTIES",value:fmt(e.casualty,true),tone:"loss"}],result:`${s.legitimacy.toFixed(1)}% CURRENT LEGITIMACY`};
  if(metric==="resistance") return{title:"Domestic Resistance",equation:"prior resistance + forced-intake pressure + coercive policy effects − legitimacy damping",basis:"AUTHORITATIVE STATE // DAILY MODIFIERS",rows:[{label:"CURRENT RESISTANCE",value:`${s.resistance.toFixed(1)}%`},{label:"FORCED INTAKE",value:fmt(s.forced,true)},{label:"LEGITIMACY",value:`${s.legitimacy.toFixed(1)}%`}],result:`${s.resistance.toFixed(1)}% CURRENT RESISTANCE`};
  if(metric==="front") return{title:"Western Front Position",equation:"prior position + tempo pressure + maneuver payoff + force ratio + intelligence − shortages",basis:"PROJECTED // RESOLVES AT DAY CLOSE",rows:[{label:"CURRENT POSITION",value:`${s.front>=0?"+":""}${s.front.toFixed(1)} KM`},{label:"VICTORY THRESHOLD",value:"+12.0 KM"},{label:"DEFEAT THRESHOLD",value:"−12.0 KM"},{label:"ENEMY STRENGTH",value:fmt(s.enemy,true)}],result:`${s.front>=0?"+":""}${s.front.toFixed(1)} KM CURRENT LINE`};
  if(metric==="desertion") return{title:"Personnel Flight",equation:"attempted desertion − patrol interceptions = net force deduction",basis:"PROJECTED // CONTINUOUS TODAY",rows:[{label:"ATTEMPTED DESERTION",value:fmt(e.desertion,true)},{label:"INTERCEPTED",value:`−${fmt(e.intercepted,true)}`},{label:"PATROL COMMITMENT",value:fmt(s.patrolCommitment,true)},{label:"DESERTION PRESSURE",value:`${s.desertionPressure.toFixed(1)}%`}],result:`${fmt(e.netDesertion,true)} PROJECTED NET FORCE LOSS`};
  if(metric==="doctrine") return{title:"Insight Point Position",equation:"verified-win awards − internalization costs",basis:"AUTHORITATIVE CAMPAIGN LEDGER",rows:[{label:"AVAILABLE POINTS",value:fmt(s.doctrine,true)},{label:"LIFETIME EARNED",value:fmt(s.doctrineEarned,true)},{label:"VERIFIED WINS",value:String(s.doctrineWinAwards.length)},{label:"INTERNALIZED TECHS",value:String(s.unlocked.length)}],result:`${fmt(s.doctrine,true)} INSIGHT POINTS AVAILABLE`};
  return{title:"Current State Decomposition",equation:"current stored value + active deterministic modifiers",basis:"AUTHORITATIVE STATE",rows:[],result:"SEE CURRENT FACTORS",uncertainties:["A metric-specific equation has not yet been registered. This is an audit gap, not a universal formula."]};
};

export const auditConceptCoverage=(tokens:string[])=>tokens.filter(token=>!CONCEPTS[token]);
