import { GameState, Resource, coverage, estimateDay, fmt, projectForceGeneration, projectProduction } from "./game";

export type SemanticTag = "ACTION"|"INSPECT"|"CONCEPT"|"MODULE_LINK"|"STATUS"|"ATMOSPHERE"|"STRUCTURE";
export type Concept = { id:string; label:string; definition:string; normal?:string; consequence:string; control?:{label:string;family?:string;module:string}; related:string[] };
export type CalculationRow = { label:string; value:string; concept?:string; tone?:"loss"|"gain"|"neutral" };
export type Calculation = { title:string; equation:string; basis:string; rows:CalculationRow[]; result:string; uncertainties?:string[] };

export const replacementReserveForProjection=(projection:ReturnType<typeof projectForceGeneration>)=>Math.max(0,projection.effectiveGraduates-Math.max(0,projection.deployableAssigned-projection.reserveReleased));

export const CONCEPTS:Record<string,Concept> = {
  "industrial-health":{id:"industrial-health",label:"Industrial Health",definition:"Factory uptime, maintenance condition, rail throughput, and accumulated repair debt.",normal:"70–85%",consequence:"Multiplies daily output on every production line.",control:{label:"Organize Industry",family:"industry",module:"national"},related:["materiel-condition","production-target","production-coverage"]},
  "production-target":{id:"production-target",label:"Production Target",definition:"The allocation policy deciding which production line receives preferential industrial capacity.",normal:"Balanced is 25% per line",consequence:"A focused line receives 46% allocation and a specialization output bonus; other lines fall to 18%.",control:{label:"Set Production Target",family:"production",module:"national"},related:["industrial-health","munitions","production-coverage"]},
  "production-coverage":{id:"production-coverage",label:"Days of Coverage",definition:"How many days the current stock can sustain the current daily use rate.",normal:"5+ days stable // below 2 days critical",consequence:"Short lines penalize Readiness, Equipment, Materiel, and battlefield conversion.",control:{label:"Set Production Target",family:"production",module:"national"},related:["munitions","operational-tempo","industrial-health"]},
  "lines-below-two-days":{id:"lines-below-two-days",label:"Lines Below Two Days",definition:"Count of production lines whose stock is less than twice their current daily use.",normal:"0",consequence:"Each shortage contributes to daily degradation and reduces maneuver confidence.",control:{label:"Set Production Target",family:"production",module:"national"},related:["production-coverage","industrial-health","readiness"]},
  "munitions":{id:"munitions",label:"Munitions",definition:"Current usable shell, rocket, missile, and ammunition stock available to the operational system.",normal:"5+ days of coverage",consequence:"Low stock increases casualties and constrains tempo and maneuver selection.",control:{label:"Set Production Target",family:"production",module:"national"},related:["production-coverage","industrial-health","operational-tempo"]},
  "maintenance-debt":{id:"maintenance-debt",label:"Maintenance Debt",definition:"Accumulated deferred repair, bearing wear, tooling damage, and transport fatigue carried by the industrial system.",normal:"0–30",consequence:"Reduces the Production circuit condition factor. Overtime and retooling increase it; maintenance posture reduces it.",control:{label:"Organize Industry",family:"industry",module:"national"},related:["industrial-health","production-target","production-coverage"]},
  "workforce-factor":{id:"workforce-factor",label:"Workforce Factor",definition:"Available civilian workforce divided by the campaign industrial baseline, clamped to the circuit operating range.",normal:"90–104%",consequence:"Multiplies output on every production line before specialization and policy effects.",control:{label:"Define Service Obligation",family:"service",module:"military"},related:["industrial-health","training-queue","production-target"]},
  "retooling-loss":{id:"retooling-loss",label:"Retooling Loss",definition:"One-resolution conversion penalty applied when industrial allocation changes target.",normal:"0% while stable",consequence:"Changing target cuts all line output by 28% for the conversion day before the new allocation takes effect.",control:{label:"Set Production Target",family:"production",module:"national"},related:["production-target","maintenance-debt","production-coverage"]},
  "training-queue":{id:"training-queue",label:"Training Queue",definition:"Recruits waiting for admission into a training cohort. They are not yet soldiers.",normal:"0.5–1.5 capacity-days",consequence:"A large queue delays the conversion of enlistment into Armed Forces.",control:{label:"Provision Training Capacity",family:"training-capacity",module:"military"},related:["training-capacity","training-duration","graduates"]},
  "training-capacity":{id:"training-capacity",label:"Training Capacity",definition:"Maximum recruits that can be admitted to training each day.",consequence:"Capacity above intake contracts backlog; capacity below intake expands it.",control:{label:"Provision Training Capacity",family:"training-capacity",module:"military"},related:["training-queue","graduates"]},
  "training-cohort":{id:"training-cohort",label:"Training Cohort",definition:"A dated body of admitted recruits moving through the current training standard together.",normal:"At least one cohort graduating before replacement demand peaks",consequence:"A cohort adds no soldiers until its remaining training days reach zero; admission-day quality determines effective graduates.",control:{label:"Set Training Standard",family:"training-standard",module:"military"},related:["training-capacity","graduates","training-queue"]},
  "graduates":{id:"graduates",label:"Effective Graduates",definition:"Quality-adjusted people who have completed a dated training cohort.",consequence:"They join Armed Forces, then receive an assignment: equipped field duty or the replacement reserve. They never convert into equipment.",control:{label:"Set Training Standard",family:"training-standard",module:"military"},related:["training-cohort","equipment-assignment","replacement-reserve","deployable-force"]},
  "equipment-assignment":{id:"equipment-assignment",label:"Field Equipment Assignment",definition:"The share of trained people issued serviceable weapons, vehicles, radios, and support equipment for field duty.",normal:"75–90% of graduates equipped",consequence:"People without serviceable kit remain trained personnel in Reserve; equipment coverage never replaces or becomes personnel.",control:{label:"Secure External Supply",family:"supply",module:"diplomacy"},related:["graduates","replacement-reserve","equipment-coverage","deployable-force"]},
  "replacement-reserve":{id:"replacement-reserve",label:"Replacement Reserve",definition:"Effective graduates not deployed today, including both unequipped personnel and equipped personnel who did not clear the readiness gate.",normal:"The smallest remainder consistent with equipment and readiness",consequence:"These people remain trained members of Armed Forces and enter Reserve; they are not equipment and do not add to Deployable Personnel until later assignment.",control:{label:"Set Training and Equipment Policy",family:"training-standard",module:"military"},related:["graduates","equipment-assignment","readiness","deployable-force"]},
  "readiness":{id:"readiness",label:"Readiness",definition:"Share of the field force presently able to execute its assigned mission.",normal:"65–85%",consequence:"Multiplies Deployable Force when Effective Force is calculated.",control:{label:"Set Operational Tempo",family:"tempo",module:"military"},related:["deployable-force","equipment-coverage","operational-tempo"]},
  "equipment-coverage":{id:"equipment-coverage",label:"Equipment Coverage",definition:"Share of field formations with serviceable assigned weapons, vehicles, radios, and support equipment.",normal:"75–90%",consequence:"Multiplies Deployable Force in Effective Force.",control:{label:"Secure External Supply",family:"supply",module:"diplomacy"},related:["readiness","deployable-force","industrial-health"]},
  "deployable-force":{id:"deployable-force",label:"Deployable Personnel",definition:"Trained, equipped, ready people currently available for field duty.",consequence:"Reinforcements add people only after graduation, field-equipment assignment, and the readiness gate. Casualties, net desertion, and rear-area commitments remove them.",control:{label:"Define Service Obligation",family:"service",module:"military"},related:["readiness","equipment-coverage","replacement-reserve","training-queue"]},
  "operational-tempo":{id:"operational-tempo",label:"Operational Tempo",definition:"Standing exchange rate between supply, casualties, and battlefield pressure.",consequence:"Changes daily casualty, supply-use, and front-pressure multipliers.",control:{label:"Set Operational Tempo",family:"tempo",module:"military"},related:["munitions","readiness","pressure"]},
  "front-movement":{id:"front-movement",label:"Front Movement",definition:"The disclosed change in the campaign line, measured against the current operational position and the day-resolution thresholds.",normal:"Between −12.0 KM and +12.0 KM",consequence:"Movement records territorial control without revealing an unobserved future result.",control:{label:"Select Campaign Maneuver",module:"campaign"},related:["frontage","force-ratio","operational-tempo"]},
  "pressure":{id:"pressure",label:"Battlefield Pressure",definition:"The current exchange of friendly pressure, enemy pressure, local force conversion, and operational tempo in the visible sector.",consequence:"Pressure changes the opportunity to move the line, but it is not itself a command or a guaranteed outcome.",control:{label:"Select Campaign Maneuver",module:"campaign"},related:["front-movement","force-ratio","operational-tempo"]},
  "reserve":{id:"reserve",label:"Replacement Reserve",definition:"Trained personnel held outside today's deployable force and available for later assignment when the readiness and equipment gates permit.",normal:"A positive depth is preferred before high-exposure action",consequence:"Releasing reserve increases present headcount while reducing continuity for later days.",control:{label:"Release the Replacement Reserve",module:"military"},related:["replacement-reserve","deployable-force","readiness"]},
  "formation":{id:"formation",label:"Formation",definition:"The organized force package whose personnel, equipment, readiness, frontage, network, and supply conditions determine local combat power.",consequence:"Formation geometry limits how much assigned force becomes useful force in the active sector.",control:{label:"Select Campaign Maneuver",module:"campaign"},related:["force-commitment","frontage","effective-committed-force"]},
  "route":{id:"route",label:"Operational Route",definition:"A disclosed approach or supply path through the active sector, evaluated through terrain, ground, network, and supply conditions.",consequence:"A route can improve access or expose the force; its existence does not assert that movement has already occurred.",control:{label:"Select Campaign Maneuver",module:"campaign"},related:["operational-supply","ground-condition","command-network"]},
  "opening":{id:"opening",label:"Operational Opening",definition:"A visible temporary weakness or breakthrough window in the current situation narrative and maneuver docket.",consequence:"An opening changes which maneuver may be worth comparing; it never authorizes an order by itself.",control:{label:"Select Campaign Maneuver",module:"campaign"},related:["front-movement","enemy-posture","execution-confidence"]},
  "position":{id:"position",label:"Current Position",definition:"The present disclosed location of the campaign line and the active operational problem, not an assertion about hidden enemy actuality.",consequence:"Position supplies context for movement, force ratio, and maneuver comparison.",control:{label:"Open Campaign",module:"campaign"},related:["front-movement","campaign-synopsis","enemy-forward-deployment"]},
  "force-commitment":{id:"force-commitment",label:"Force Commitment",definition:"Deployable soldiers assigned to the selected maneuver and exposed to its local conditions.",normal:"Enough to fill useful frontage without exceeding 135%",consequence:"Commitment determines the population exposed to losses; excess commitment can become congestion instead of power.",control:{label:"Select Campaign Maneuver",module:"campaign"},related:["frontage","effective-committed-force","force-ratio"]},
  "effective-committed-force":{id:"effective-committed-force",label:"Effective Committed Force",definition:"Committed personnel multiplied once by a disclosed weighted blend of readiness, equipment, terrain, ground, network, supply, and intelligence.",consequence:"It is the complete friendly numerator used by the local force ratio. Uncommitted personnel are not quietly added as combat power.",control:{label:"Select Campaign Maneuver",module:"campaign"},related:["force-commitment","force-ratio","readiness"]},
  "force-ratio":{id:"force-ratio",label:"Effective Force Ratio",definition:"Friendly effective force divided by enemy effective force in the active sector.",normal:"1.00 or greater",consequence:"Both personnel bases and both condition conversions are disclosed in the same report; the resulting ratio changes losses and battlefield pressure.",control:{label:"Select Campaign Maneuver",module:"campaign"},related:["effective-committed-force","frontage","pressure"]},
  "frontage":{id:"frontage",label:"Frontage",definition:"The useful width and carrying capacity available for formations in the active terrain.",normal:"70–135% saturation",consequence:"Below capacity leaves power unused; above 135% produces congestion and declining conversion efficiency.",control:{label:"Select Campaign Maneuver",module:"campaign"},related:["force-commitment","terrain-conversion","force-ratio"]},
  "terrain-conversion":{id:"terrain-conversion",label:"Terrain Conversion",definition:"Fraction of assigned force that the sector's dominant terrain permits to become local combat power.",consequence:"Prepared ridges and narrow corridors reduce conversion; open basins and lowlands preserve more power.",control:{label:"Select Campaign Maneuver",module:"campaign"},related:["frontage","ground-condition","effective-committed-force"]},
  "ground-condition":{id:"ground-condition",label:"Ground Condition",definition:"Passability and obstacle state imposed by mines, saturation, cratering, or dry passage.",consequence:"Changes both power conversion and friendly loss exposure.",control:{label:"Select Campaign Maneuver",module:"campaign"},related:["terrain-conversion","frontage","effective-committed-force"]},
  "command-network":{id:"command-network",label:"Command Network",definition:"Ability to transmit intent, coordinate supporting arms, and classify friendly movement in the active sector.",normal:"Intermittent or better",consequence:"Degraded or severed networks sharply reduce committed-force conversion unless Doctrine preserves autonomy.",control:{label:"Restore the Command Net",module:"campaign"},related:["intelligence","effective-committed-force","networked-command"]},
  "operational-supply":{id:"operational-supply",label:"Operational Supply",definition:"Fraction of demanded ammunition, fuel, transport, and repair capacity reaching the committed force at its selected tempo.",consequence:"Interdiction and high tempo reduce local power even when national stocks remain positive.",control:{label:"Secure External Supply",family:"supply",module:"diplomacy"},related:["munitions","operational-tempo","effective-committed-force"]},
  "intelligence":{id:"intelligence",label:"Operational Intelligence",definition:"Quality of classification used to estimate enemy strength, identify dispositions, and convert committed force into useful battlefield power.",normal:"42–70 before specialist doctrine",consequence:"Raises operational conversion and Execution Confidence while revealing more enemy orders.",control:{label:"Conduct Statecraft",family:"statecraft",module:"diplomacy"},related:["execution-confidence","enemy-orders","effective-committed-force"]},
  "execution-confidence":{id:"execution-confidence",label:"Execution Confidence",definition:"The disclosed probability that a selected maneuver clears the zero-margin threshold after the sealed field-friction draw is applied.",normal:"50% or greater",consequence:"The field-friction draw is subtracted from confidence to select Clean Execution, Executed With Friction, Disrupted, or Operational Collapse.",control:{label:"Select and Prepare a Maneuver",module:"campaign"},related:["intelligence","readiness","equipment-coverage","enemy-adaptation"]},
  "casualty-exposure":{id:"casualty-exposure",label:"Friendly Loss Exposure",definition:"The disclosed minimum and maximum friendly losses across the four possible maneuver result bands.",consequence:"Losses are drawn from the forward-deployed force, reduce Armed and Deployable Force, and create domestic casualty burden.",control:{label:"Select a Campaign Maneuver",module:"campaign"},related:["force-commitment","force-ratio","ground-condition"]},
  "enemy-forward-deployment":{id:"enemy-forward-deployment",label:"Assessed Enemy Local Deployment",definition:"Enemy personnel assessed in the active sector: theater forward deployment allocated by that sector's share of the enemy disposition.",normal:"Read with its disclosed local uncertainty band",consequence:"The local personnel estimate is converted once into enemy effective force and used directly by the ratio; theater total remains supporting context only.",control:{label:"Improve Classification or Change Enemy Posture",module:"campaign"},related:["intelligence","enemy-posture","force-ratio","enemy-orders"]},
  "campaign-synopsis":{id:"campaign-synopsis",label:"Campaign Synopsis",definition:"The current theater, sector, operational problem, commander question, standing order, and authorized maneuver set assembled into one daily command brief.",consequence:"The synopsis explains why the problem exists and what must be decided; the sealed daily situation supplies the underlying evidence.",control:{label:"Open Campaign",module:"campaign"},related:["operational-fact","enemy-forward-deployment","execution-confidence"]},
  "target-of-opportunity":{id:"target-of-opportunity",label:"Target of Opportunity",definition:"A rare individual or irregular operation opened by a sealed one-in-three roll on eligible campaign days. Day 1 is always excluded, and an opened assignment remains available until day resolution.",normal:"At most one event per eligible day; every event spine appears only once in a campaign instance",consequence:"Its immediate result changes same-day authoritative state and can alter the operation still awaiting day close. It never consumes a strategic order.",control:{label:"Respond Before Day Resolution",module:"campaign"},related:["intelligence","pressure","enemy-forward-deployment"]},
  "legitimacy":{id:"legitimacy",label:"Legitimacy",definition:"Public willingness to accept the state's losses, coercion, shortages, and account of the war.",normal:"50–75",consequence:"At zero the campaign ends; low Legitimacy accelerates resistance, desertion pressure, and continuity failure.",control:{label:"Administer the Butcher's Bill",family:"casualty-politics",module:"national"},related:["resistance","casualty-burden","atrocity-exposure"]},
  "resistance":{id:"resistance",label:"Resistance",definition:"Draft evasion, strikes, sabotage, noncompliance, clandestine organization, and administrative friction.",normal:"Below 30",consequence:"High Resistance raises strike risk and desertion pressure and can combine with low Legitimacy into state collapse.",control:{label:"Govern Civil Allocation",family:"home-front",module:"national"},related:["legitimacy","forced-intake-burden","shortage-burden"]},
  "desertion-pressure":{id:"desertion-pressure",label:"Desertion Pressure",definition:"Daily rate driver for attempted personnel flight from the armed force.",normal:"Below 20",consequence:"Casualties, low readiness, low legitimacy, and organized resistance raise attempted desertion at resolution.",control:{label:"Process Desertion",family:"desertion",module:"military"},related:["legitimacy","resistance","deployable-force"]},
  "casualty-burden":{id:"casualty-burden",label:"Casualty Burden",definition:"Daily friendly losses divided by the state's current legitimacy absorption rate.",normal:"Below 1.0",consequence:"Directly reduces Legitimacy and contributes to Resistance growth.",control:{label:"Administer the Butcher's Bill",family:"casualty-politics",module:"national"},related:["legitimacy","resistance","force-commitment"]},
  "forced-intake-burden":{id:"forced-intake-burden",label:"Forced Intake Burden",definition:"Daily coerced military intake normalized against the civil administration's processing threshold.",normal:"Below 0.5",consequence:"Directly increases Resistance regardless of whether the recruits reach training.",control:{label:"Define Service Obligation",family:"service",module:"military"},related:["resistance","training-queue","legitimacy"]},
  "shortage-burden":{id:"shortage-burden",label:"Shortage Burden",definition:"Domestic political cost generated by production lines closing below two days of operational coverage.",normal:"0",consequence:"Reduces Legitimacy and raises Resistance while critical war stocks remain short.",control:{label:"Set Production Target",family:"production",module:"national"},related:["production-coverage","legitimacy","resistance"]},
  "atrocity-exposure":{id:"atrocity-exposure",label:"Atrocity Exposure",definition:"Accumulated evidence that prohibited methods were authorized and attributable to the state.",normal:"0",consequence:"Continuously reduces Legitimacy and creates reciprocal and diplomatic consequences.",control:{label:"Atrocities",module:"doctrine"},related:["legitimacy","reciprocity","casualty-burden"]},
  "fiscal-stress":{id:"fiscal-stress",label:"Fiscal Stress",definition:"Political burden created when immediately spendable Treasury falls below the state's operating threshold.",normal:"Treasury above 40 B",consequence:"Reduces Legitimacy as arrears, ration failures, and unpaid obligations become visible.",control:{label:"Finance Mobilization",family:"finance",module:"national"},related:["legitimacy","resistance","production-target"]},
  "diplomatic-trust":{id:"diplomatic-trust",label:"Diplomatic Trust",definition:"An actor's expectation that the state will honor disclosed commitments and preserve the relationship after receiving value.",normal:"50–75 for usable partners",consequence:"Raises aid delivery and suppresses betrayal pressure; low Trust can suspend pipelines and treaty cooperation.",control:{label:"Conduct Statecraft",family:"statecraft",module:"diplomacy"},related:["foreign-leverage","aid-pipeline","betrayal-pressure"]},
  "foreign-leverage":{id:"foreign-leverage",label:"Foreign Leverage",definition:"The actor's accumulated ability to impose conditions on the state because access, debt, intelligence, or obligations cannot be replaced cheaply.",normal:"Below 45",consequence:"Raises betrayal pressure and makes future cooperation more expensive even when Trust remains high.",control:{label:"Bind Foreign Obligations",family:"treaties",module:"diplomacy"},related:["foreign-dependency","diplomatic-trust","treaty-obligation"]},
  "foreign-dependency":{id:"foreign-dependency",label:"Foreign Dependency",definition:"Share of the relationship's military or economic value that the state cannot presently substitute domestically.",normal:"Below 30",consequence:"Amplifies betrayal pressure and converts interrupted aid into production and operational shocks.",control:{label:"Secure External Supply",family:"supply",module:"diplomacy"},related:["aid-pipeline","foreign-leverage","betrayal-pressure"]},
  "treaty-obligation":{id:"treaty-obligation",label:"Treaty Obligation",definition:"Callable duty accumulated through ratified defense, transit, intelligence, and alliance instruments.",consequence:"Can be spent to request foreign forces or access; refusing calls destroys Trust and Leverage.",control:{label:"Service Alliance Obligations",family:"alliance-obligations",module:"diplomacy"},related:["diplomatic-trust","foreign-leverage","aid-pipeline"]},
  "aid-pipeline":{id:"aid-pipeline",label:"Aid Pipeline",definition:"Persistent foreign delivery capacity converted each day into munitions, treasury liquidity, and intelligence according to Trust and betrayal pressure.",normal:"10+ for active partners",consequence:"Delivers less when Trust falls or betrayal pressure rises; it compounds across the campaign rather than creating a single grant.",control:{label:"Bind Foreign Obligations",family:"treaties",module:"diplomacy"},related:["diplomatic-trust","foreign-dependency","betrayal-pressure"]},
  "sanctions-exposure":{id:"sanctions-exposure",label:"Sanctions Exposure",definition:"Degree to which an actor and its routes are isolated from finance, transport, insurance, components, and legal market access.",normal:"Below 25",consequence:"Aggregate exposure imposes daily Materiel Condition drag and can interrupt neutral transit.",control:{label:"Administer Sanctions",family:"sanctions",module:"diplomacy"},related:["aid-pipeline","foreign-leverage","production-coverage"]},
  "betrayal-pressure":{id:"betrayal-pressure",label:"Betrayal Pressure",definition:"Risk index composed from Dependency, foreign Leverage, distrust, and broker incentives.",normal:"Below 35%",consequence:"Reduces foreign deliveries before any overt rupture and marks relationships vulnerable to later contingent events.",control:{label:"Conduct Statecraft",family:"statecraft",module:"diplomacy"},related:["diplomatic-trust","foreign-leverage","foreign-dependency"]},
  "enemy-orders":{id:"enemy-orders",label:"Enemy Orders",definition:"The adversary receives three orders per day: one Operations posture, one Production target, and one Countermeasure.",normal:"One to three orders observed according to Intelligence",consequence:"Orders alter enemy pressure, combat power, supply use, and direct counters before the player's operation resolves.",control:{label:"Improve Intelligence",family:"statecraft",module:"diplomacy"},related:["enemy-posture","enemy-production","enemy-countermeasure"]},
  "enemy-posture":{id:"enemy-posture",label:"Enemy Operational Posture",definition:"The adversary's daily exchange rate between readiness, munitions, battlefield power, casualties, and pressure.",consequence:"Counterstrokes and assaults impose more pressure and losses but consume enemy readiness and supply; reconstitution does the reverse.",control:{label:"Select Campaign Maneuver",module:"campaign"},related:["enemy-orders","force-ratio","enemy-doctrine"]},
  "enemy-production":{id:"enemy-production",label:"Enemy Production Signature",definition:"Intelligence assessment of which bottleneck receives the enemy's marginal industrial capacity.",consequence:"Munitions recovery expands enemy coverage; replacement equipment restores force conversion; signal denial supports countermeasures.",control:{label:"Conduct Statecraft",family:"statecraft",module:"diplomacy"},related:["enemy-orders","enemy-countermeasure","intelligence"]},
  "enemy-countermeasure":{id:"enemy-countermeasure",label:"Enemy Countermeasure",definition:"The adversary's daily response to the player's most frequently observed maneuver pattern.",consequence:"Can reduce network conversion, increase friendly losses, protect enemy fires, or deepen obstacle effects.",control:{label:"Vary Campaign Maneuvers",module:"campaign"},related:["enemy-adaptation","enemy-orders","execution-confidence"]},
  "enemy-doctrine":{id:"enemy-doctrine",label:"Enemy Doctrine",definition:"Accumulated institutional observation earned as enemy methods operate and survive across daily resolutions.",consequence:"Raises reinforcement capacity and supplies thresholds for later enemy methods and unit behaviors.",control:{label:"Deny Enemy Observation",module:"campaign"},related:["enemy-adaptation","enemy-posture","enemy-orders"]},
  "enemy-adaptation":{id:"enemy-adaptation",label:"Enemy Adaptation",definition:"Per-maneuver memory created when the player repeats an operational method after the enemy has already observed it.",normal:"0–2",consequence:"Each level removes 1.5 percentage points from that maneuver's Execution Confidence, up to 12 points.",control:{label:"Vary Campaign Maneuvers",module:"campaign"},related:["enemy-countermeasure","execution-confidence","enemy-doctrine"]},
};

export const calculationFor=(metric:string,s:GameState):Calculation=>{
  const e=estimateDay(s);
  if(metric==="materiel") {const p=projectProduction(s),m=p.lines.find(x=>x.resource==="munitions")!;return {title:"Production Circuit at Day Resolution",equation:"stock + (base output × allocation × workforce × condition × policy × specialization × retooling) − operational use",basis:"PROJECTED // CURRENT POLICIES AND ORDERS",rows:[{label:"OPENING MUNITIONS",value:fmt(m.opening,true),concept:"munitions"},{label:"CIRCUIT OUTPUT",value:`+${fmt(m.output,true)}`,concept:"industrial-health",tone:"gain"},{label:"OPERATIONAL USE",value:`−${fmt(m.use,true)}`,concept:"operational-tempo",tone:"loss"},{label:"WORKFORCE FACTOR",value:`${Math.round(p.workforceFactor*100)}%`,concept:"workforce-factor"},{label:"CONDITION FACTOR",value:`${Math.round(p.conditionFactor*100)}%`,concept:"industrial-health"},{label:"MAINTENANCE DEBT",value:`${p.maintenanceDebtAfter.toFixed(0)} / 100`,concept:"maintenance-debt"},{label:"PRODUCTION TARGET",value:p.target.toUpperCase(),concept:"production-target"},{label:"RETOOLING",value:p.retooled?"−28% TODAY":"NONE",concept:"retooling-loss"},...p.lines.map(line=>({label:`${line.resource.toUpperCase()} COVERAGE`,value:`${line.coverage.toFixed(1)} DAYS`,concept:"production-coverage",tone:line.status==="critical"?"loss" as const:"neutral" as const}))],result:`${fmt(m.closing,true)} PROJECTED MUNITIONS // ${p.shortages} CRITICAL LINES`};}
  if(metric==="training") {const f=projectForceGeneration(s),replacementReserve=replacementReserveForProjection(f);return{title:"Reinforcement Pipeline",equation:"recruits → induction → training cohorts → effective graduates; field equipment × readiness + reserve recall → deployable reinforcements",basis:"PROJECTED // NEXT RESOLUTION",rows:[{label:"OPENING QUEUE",value:fmt(f.queueOpening,true),concept:"training-queue"},{label:"DAILY INTAKE",value:`+${fmt(f.grossIntake,true)}`,concept:"training-queue",tone:"gain"},{label:"ADMITTED TODAY",value:fmt(f.admitted,true),concept:"training-capacity"},{label:"ACTIVE COHORTS",value:String(f.cohortsClosing),concept:"training-cohort"},{label:"EFFECTIVE GRADUATES",value:fmt(f.effectiveGraduates,true),concept:"graduates",tone:"gain"},{label:"FIELD-EQUIPPED GRADUATES",value:fmt(f.equipmentAssigned,true),concept:"equipment-assignment"},{label:"HELD IN REPLACEMENT RESERVE",value:fmt(replacementReserve,true),concept:"replacement-reserve"},{label:"RESERVE RECALLED",value:fmt(f.reserveReleased,true),concept:"deployable-force",tone:"gain"},{label:"DEPLOYABLE REINFORCEMENTS",value:`+${fmt(f.deployableAssigned,true)}`,concept:"deployable-force",tone:"gain"}],result:`${fmt(f.deployableClosing,true)} PROJECTED DEPLOYABLE PERSONNEL`};}
  if(metric==="armed") return{title:"Effective Force",equation:"deployable force × readiness × equipment coverage",basis:"LIVE // CURRENT DAY",rows:[{label:"DEPLOYABLE FORCE",value:fmt(s.deployable,true),concept:"deployable-force"},{label:"READINESS",value:`× ${(s.readiness/100).toFixed(2)}`,concept:"readiness"},{label:"EQUIPMENT COVERAGE",value:`× ${(s.equipment/100).toFixed(2)}`,concept:"equipment-coverage"}],result:`${fmt(s.deployable*s.readiness/100*s.equipment/100,true)} EFFECTIVE FORCE`};
  if(metric==="readiness") return{title:"Readiness State",equation:"prior readiness + replacement effect − shortages − tempo debt",basis:"AUTHORITATIVE STATE // DAILY MODIFIERS",rows:[{label:"CURRENT READINESS",value:`${s.readiness.toFixed(1)}%`,concept:"readiness"},{label:"TRAINING QUALITY",value:`${s.quality.toFixed(0)}%`,concept:"training-capacity"},{label:"OPERATIONAL TEMPO",value:s.tempo.toUpperCase(),concept:"operational-tempo"},{label:"CRITICAL LINES",value:String(Object.keys(s.production).filter(k=>coverage(s,k as Resource)<2).length),concept:"lines-below-two-days"}],result:`${s.readiness.toFixed(1)}% CURRENT READINESS`};
  if(metric==="population") return{title:"Population and Labor Base",equation:"population − recorded war deaths // workforce − military intake",basis:"AUTHORITATIVE STATE",rows:[{label:"OPENING POPULATION",value:"18,420,000"},{label:"CURRENT POPULATION",value:fmt(s.population,true)},{label:"RECORDED WAR DEATHS",value:fmt(18420000-s.population,true),tone:"loss"},{label:"WORKFORCE",value:fmt(s.workforce,true)}],result:`${fmt(s.population,true)} LIVING POPULATION`};
  if(metric==="enlistment") return{title:"Daily Recruitment Intake",equation:"voluntary intake + forced intake → training queue",basis:"DAILY RATE // CURRENT POLICIES",rows:[{label:"VOLUNTARY",value:`+${fmt(s.voluntary,true)}`},{label:"FORCED",value:`+${fmt(s.forced,true)}`},{label:"TRAINING QUEUE",value:fmt(s.queue,true),concept:"training-queue"},{label:"TRAINING CAPACITY",value:fmt(s.training,true),concept:"training-capacity"}],result:`${fmt(s.voluntary+s.forced,true)} RECRUITS PER DAY`};
  if(metric==="equipment") return{title:"Equipment Coverage",equation:"serviceable field sets ÷ field sets required by deployable personnel",basis:"AUTHORITATIVE STATE",rows:[{label:"CURRENT COVERAGE",value:`${s.equipment.toFixed(1)}%`,concept:"equipment-coverage"},{label:"ARMOR STOCK",value:fmt(s.production.armor.stock,true)},{label:"FLIGHT STOCK",value:fmt(s.production.flight.stock,true)},{label:"INDUSTRIAL HEALTH",value:`${s.materiel.toFixed(1)}%`,concept:"industrial-health"}],result:`${s.equipment.toFixed(1)}% OF FIELD REQUIREMENT EQUIPPED`};
  if(metric==="treasury") return{title:"Daily Treasury Position",equation:"current treasury + baseline revenue − armed-force burden − active policy costs",basis:"PROJECTED // DAILY RESOLUTION",rows:[{label:"CURRENT TREASURY",value:`${s.treasury.toFixed(1)} B`},{label:"BASELINE REVENUE",value:"+3.4 B",tone:"gain"},{label:"ARMED-FORCE BURDEN",value:`−${(s.armed/185000).toFixed(1)} B`,tone:"loss"}],result:`${(s.treasury+3.4-s.armed/185000).toFixed(1)} B BEFORE POLICY COSTS`};
  if(metric==="legitimacy") return{title:"Political Tolerance",equation:"prior legitimacy + policy effects − casualty burden − atrocity exposure",basis:"AUTHORITATIVE STATE // PROJECTED PRESSURES",rows:[{label:"CURRENT LEGITIMACY",value:`${s.legitimacy.toFixed(1)}%`},{label:"RESISTANCE",value:`${s.resistance.toFixed(1)}%`},{label:"ATROCITY EXPOSURE",value:`${s.atrocityExposure.toFixed(1)}%`},{label:"PROJECTED CASUALTIES",value:fmt(e.casualty,true),tone:"loss"}],result:`${s.legitimacy.toFixed(1)}% CURRENT LEGITIMACY`};
  if(metric==="resistance") return{title:"Domestic Resistance",equation:"prior resistance + forced-intake pressure + coercive policy effects − legitimacy damping",basis:"AUTHORITATIVE STATE // DAILY MODIFIERS",rows:[{label:"CURRENT RESISTANCE",value:`${s.resistance.toFixed(1)}%`},{label:"FORCED INTAKE",value:fmt(s.forced,true)},{label:"LEGITIMACY",value:`${s.legitimacy.toFixed(1)}%`}],result:`${s.resistance.toFixed(1)}% CURRENT RESISTANCE`};
  if(metric==="front") return{title:"Western Front Position",equation:"prior position + tempo pressure + maneuver payoff + force ratio + intelligence − shortages",basis:"PROJECTED // RESOLVES AT DAY CLOSE",rows:[{label:"CURRENT POSITION",value:`${s.front>=0?"+":""}${s.front.toFixed(1)} KM`},{label:"VICTORY THRESHOLD",value:"+12.0 KM"},{label:"DEFEAT THRESHOLD",value:"−12.0 KM"},{label:"ENEMY STRENGTH",value:fmt(s.enemy,true)}],result:`${s.front>=0?"+":""}${s.front.toFixed(1)} KM CURRENT LINE`};
  if(metric==="reserve") return{title:"Replacement Reserve",equation:"trained personnel held outside today's deployable force",basis:"AUTHORITATIVE STATE",rows:[{label:"REPLACEMENT RESERVE",value:fmt(s.reserves,true),concept:"replacement-reserve"},{label:"DEPLOYABLE FORCE",value:fmt(s.deployable,true),concept:"deployable-force"},{label:"READINESS",value:`${s.readiness.toFixed(1)}%`,concept:"readiness"}],result:`${fmt(s.reserves,true)} PERSONNEL IN RESERVE`};
  if(metric==="desertion") return{title:"Personnel Flight",equation:"attempted flight − retained by policy − patrol interceptions = net force deduction",basis:"PROJECTED // CONTINUOUS TODAY",rows:[{label:"ATTEMPTED FLIGHT",value:fmt(e.desertion,true),concept:"desertion-pressure"},{label:"RETAINED BY POLICY",value:`−${fmt(e.retained,true)}`,concept:"legitimacy",tone:"gain"},{label:"INTERCEPTED",value:`−${fmt(e.intercepted,true)}`,concept:"desertion-pressure",tone:"gain"},{label:"PATROL COMMITMENT",value:fmt(s.patrolCommitment,true),concept:"deployable-force"},{label:"DESERTION PRESSURE",value:`${s.desertionPressure.toFixed(1)}%`,concept:"desertion-pressure"}],result:`${fmt(e.netDesertion,true)} PROJECTED NET FORCE LOSS`};
  if(metric==="doctrine") return{title:"Insight Point Position",equation:"verified-win awards − internalization costs",basis:"AUTHORITATIVE CAMPAIGN LEDGER",rows:[{label:"AVAILABLE POINTS",value:fmt(s.doctrine,true)},{label:"LIFETIME EARNED",value:fmt(s.doctrineEarned,true)},{label:"VERIFIED WINS",value:String(s.doctrineWinAwards.length)},{label:"INTERNALIZED TECHS",value:String(s.unlocked.length)}],result:`${fmt(s.doctrine,true)} INSIGHT POINTS AVAILABLE`};
  return{title:"Current State Decomposition",equation:"current stored value + active declared modifiers",basis:"AUTHORITATIVE STATE",rows:[],result:"SEE CURRENT FACTORS",uncertainties:["A metric-specific equation has not yet been registered. This is an audit gap, not a universal formula."]};
};

export const auditConceptCoverage=(tokens:string[])=>tokens.filter(token=>!CONCEPTS[token]);
