"use client";

import { useState } from "react";
import { CONCEPTS } from "./concepts";
import { fmt, projectDiplomacy, type GameState } from "./game";

function Concept({id,children}:{id:string;children:React.ReactNode}){const c=CONCEPTS[id];return <span className="term" tabIndex={0}>{children}<span className="term-tip"><b>{c.label}</b><span>{c.definition}</span>{c.normal&&<em>NORMAL // {c.normal}</em>}<strong>CONSEQUENCE // {c.consequence}</strong><a href={`?wiki=${id}`} target="_blank" rel="noreferrer">OPEN WIKI ARTICLE ↗</a></span></span>}

export function DiplomacyPanel({s}:{s:GameState}){const ledger=projectDiplomacy(s);const[selected,setSelected]=useState(ledger.actors[0]?.id??"");const actor=ledger.actors.find(a=>a.id===selected)??ledger.actors[0];return <section className="diplomacy-panel"><header><div><small>FOREIGN RELATIONS // NEXT RESOLUTION</small><b>{fmt(ledger.totalMunitions,true)} MUNITIONS INBOUND</b></div><div><small>TREASURY DELIVERY</small><b>{ledger.totalTreasury.toFixed(1)} B</b></div><div><small>INTELLIGENCE DELIVERY</small><b>+{ledger.totalIntelligence}</b></div><div><small>HIGHEST BETRAYAL PRESSURE</small><b>{Math.round(ledger.highestBetrayalRisk*100)}%</b></div></header><div className="diplomacy-workspace"><nav>{ledger.actors.map(a=><button className={a.id===actor.id?"selected":""} onClick={()=>setSelected(a.id)} key={a.id}><span>{a.role.toUpperCase()}</span><b>{a.name}</b><small>TRUST {a.trust.toFixed(0)} // LEVERAGE {a.leverage.toFixed(0)}</small></button>)}</nav>{actor&&<article><div><small>{actor.role.toUpperCase()} // {actor.id.toUpperCase()}</small><h3>{actor.name}</h3><p>{actor.interest}</p></div><div className="actor-metrics"><div><Concept id="diplomatic-trust">TRUST</Concept><b>{actor.trust.toFixed(1)}</b><small>{actor.trustChange>=0?"+":""}{actor.trustChange.toFixed(1)}/day</small></div><div><Concept id="foreign-leverage">LEVERAGE</Concept><b>{actor.leverage.toFixed(1)}</b><small>{actor.leverageChange>=0?"+":""}{actor.leverageChange.toFixed(1)}/day</small></div><div><Concept id="foreign-dependency">DEPENDENCY</Concept><b>{actor.dependency.toFixed(1)}</b><small>{actor.dependencyChange>=0?"+":""}{actor.dependencyChange.toFixed(1)}/day</small></div><div><Concept id="treaty-obligation">OBLIGATION</Concept><b>{actor.obligation.toFixed(1)}</b><small>callable duty</small></div><div><Concept id="aid-pipeline">AID PIPELINE</Concept><b>{actor.aidPipeline.toFixed(1)}</b><small>{fmt(actor.munitionsDelivered,true)} munitions/day</small></div><div><Concept id="sanctions-exposure">SANCTIONS</Concept><b>{actor.sanctionsExposure.toFixed(1)}</b><small>external isolation</small></div><div className={actor.betrayalRisk>.55?"critical":""}><Concept id="betrayal-pressure">BETRAYAL PRESSURE</Concept><b>{Math.round(actor.betrayalRisk*100)}%</b><small>dependency + leverage + distrust</small></div></div></article>}</div><footer>{ledger.totalSanctionsDrag.toFixed(2)} MATERIEL CONDITION LOST TO AGGREGATE SANCTIONS EXPOSURE // SELECT ACTOR TO INSPECT</footer></section>}
