"use client";

import { CONCEPTS } from "./concepts";
import { projectDomestic, type GameState } from "./game";
import { openWikiApplet } from "./wiki-events";

function Concept({id,children}:{id:string;children:React.ReactNode}){const c=CONCEPTS[id];return <span className="term" role="button" tabIndex={0} onClick={()=>openWikiApplet(id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")openWikiApplet(id)}}>{children}<span className="term-tip"><b>{c.label}</b><span>{c.definition}</span>{c.normal&&<em>NORMAL // {c.normal}</em>}<strong>CONSEQUENCE // {c.consequence}</strong><button onClick={e=>{e.stopPropagation();openWikiApplet(id)}}>OPEN WIKI APPLET</button><a href={`?wiki=${id}`} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>OPEN EXTERNALLY ↗</a></span></span>}

export function DomesticStatePanel({s}:{s:GameState}){const d=projectDomestic(s);const burdens=[["CASUALTY BURDEN",d.casualtyBurden,"casualty-burden"],["FORCED INTAKE",d.forcedIntakeBurden,"forced-intake-burden"],["SHORTAGES",d.shortageBurden,"shortage-burden"],["ATROCITY",d.atrocityBurden,"atrocity-exposure"],["FISCAL STRESS",d.fiscalBurden,"fiscal-stress"]] as const;return <section className="domestic-panel"><header><div><small>DOMESTIC STATE // NEXT RESOLUTION</small><b>{d.collapseRisk>.35?"CONTINUITY THREATENED":d.strikeRisk>.5?"ORGANIZED FRICTION":"STATE ABSORBING LOSS"}</b></div><div><small>STRIKE RISK</small><b>{Math.round(d.strikeRisk*100)}%</b></div><div><small>COLLAPSE RISK</small><b>{Math.round(d.collapseRisk*100)}%</b></div></header><div className="domestic-transition"><div><Concept id="legitimacy">LEGITIMACY</Concept><b>{d.legitimacyOpening.toFixed(1)} → {d.legitimacyClosing.toFixed(1)}</b><small>{d.legitimacyChange>=0?"+":""}{d.legitimacyChange.toFixed(1)} projected</small></div><div><Concept id="resistance">RESISTANCE</Concept><b>{d.resistanceOpening.toFixed(1)} → {d.resistanceClosing.toFixed(1)}</b><small>{d.resistanceChange>=0?"+":""}{d.resistanceChange.toFixed(1)} projected</small></div><div><Concept id="desertion-pressure">DESERTION PRESSURE</Concept><b>{d.desertionPressureChange>=0?"+":""}{d.desertionPressureChange.toFixed(1)}</b><small>daily pressure change</small></div></div><div className="domestic-burdens">{burdens.map(([label,value,id])=><div key={label}><Concept id={id}>{label}</Concept><b>{Number(value).toFixed(2)}</b></div>)}</div><footer>POLICY MODIFIER // LEGITIMACY {d.policyLegitimacy>=0?"+":""}{d.policyLegitimacy.toFixed(1)} // RESISTANCE {d.policyResistance>=0?"+":""}{d.policyResistance.toFixed(1)}</footer></section>}
