"use client";

import { useEffect, useMemo, useState } from "react";
import { CONCEPTS } from "./concepts";
import { DOCTRINES, FAMILIES, MANEUVERS, SITUATIONS } from "./game";
import { DOMESTIC_SUB_MISSIONS, NETWORK_SUB_MISSIONS } from "./submission-schema";
import { SUB_MISSION_FRAMES, realizationsForArchetype } from "./sub-mission-content";

export type FieldManualNode={id:string;label:string;summary:string;body:string;related:string[];control?:{label:string;module:string;family?:string}};
const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const core:FieldManualNode[]=[
  {id:"resolution",label:"Resolution",summary:"The authoritative end-of-day reckoning.",body:"Resolution applies active orders in a fixed sequence, preserves their ledgers, rotates sealed daily missions, and opens the next day.",related:["Actions","Owned Effects","Contingent Effects","Campaign Event Director"]},
  {id:"actions",label:"Actions",summary:"The shared three-order daily command budget.",body:"Main Campaign, Domestic Front, Command Network, Production, Military, and Diplomacy draw from one daily pool. Unused orders lapse.",related:["Resolution","Campaign Synopsis"]},
  {id:"execution-confidence",label:"Execution Confidence",summary:"The disclosed probability input for a maneuver outcome band.",body:"Maneuver base, intelligence, readiness, equipment, shortages, field proofs, doctrine, enemy adaptation, and campaign condition are summed once and clamped from 5% to 95%.",related:["Intelligence","Readiness","Equipment Coverage","Enemy Adaptation","Strategic Condition"]},
  {id:"standing-order",label:"Standing Order",summary:"The operation prosecuted when no Main Campaign maneuver is issued.",body:"Standing tempo still consumes supply, incurs loss, and contests the front. Inaction is a policy, not a skipped simulation.",related:["Operational Tempo","Resolution","Front Movement"]},
  {id:"owned-effects",label:"Owned Effects",summary:"Guaranteed consequences applied by a validated command.",body:"Owned effects do not depend on a resolution roll and are disclosed before issue.",related:["Contingent Effects","Actions","Resolution"]},
  {id:"contingent-effects",label:"Contingent Effects",summary:"Bounded consequences resolved from the sealed daily record.",body:"Contingencies expose their range or risk before issue and remain reproducible from the campaign seed and authoritative state.",related:["Owned Effects","Execution Confidence","Resolution"]},
  {id:"strategic-condition",label:"Strategic Condition",summary:"The disclosed daily condition modifying campaign circuits.",body:"The condition remains sealed for the day and changes named production, supply, casualty, desertion, confidence, pressure, or political terms.",related:["Resolution","Campaign Synopsis"]},
];

const buildCatalog=()=>{
  const nodes:FieldManualNode[]=[...core,...Object.values(CONCEPTS).map(concept=>({id:concept.id,label:concept.label,summary:concept.definition,body:`${concept.consequence}${concept.normal?` Normal: ${concept.normal}.`:""}`,related:concept.related,control:concept.control}))];
  FAMILIES.forEach(family=>{nodes.push({id:`issue-${slug(family.label)}`,label:family.label,summary:family.brief,body:`${family.choices.length} directives. One order. ${family.lock}-day family rotation.`,related:family.choices.map(choice=>choice.label),control:{label:family.label,module:family.module,family:family.id}});family.choices.forEach(choice=>nodes.push({id:`directive-${slug(choice.label)}`,label:choice.label,summary:choice.flavor,body:`Owned effects: ${choice.exact.join("; ")} Tradeoffs: ${choice.risk.join("; ")||"none disclosed"}.`,related:[family.label,"Owned Effects","Contingent Effects"],control:{label:family.label,module:family.module,family:family.id}}))});
  MANEUVERS.forEach(maneuver=>nodes.push({id:`maneuver-${slug(maneuver.label)}`,label:maneuver.label,summary:maneuver.flavor,body:`Base confidence ${Math.round(maneuver.success*100)}%. Owned commitment: ${maneuver.exact.join("; ")} Contingent result: ${maneuver.risk.join("; ")}.`,related:[maneuver.vector,"Execution Confidence","Front Movement"],control:{label:"Open Campaign",module:"campaign"}}));
  DOCTRINES.forEach(vector=>{nodes.push({id:`vector-${slug(vector.label)}`,label:vector.label,summary:`Doctrine vector administered by ${vector.authority}.`,body:`${vector.stages.length} sequential principles.`,related:vector.stages.map(stage=>stage.label),control:{label:"Open Doctrine",module:"doctrine"}});vector.stages.forEach(stage=>nodes.push({id:`doctrine-${slug(stage.label)}`,label:stage.label,summary:stage.description,body:`Cost ${stage.cost} Insight Points. ${stage.effect}`,related:[vector.label,"Execution Confidence"],control:{label:"Open Doctrine",module:"doctrine"}}))});
  SITUATIONS.forEach(situation=>nodes.push({id:`situation-${slug(situation.id)}`,label:situation.sector,summary:situation.headline,body:`${situation.briefing} Commander question: ${situation.question}`,related:["Campaign Synopsis","Execution Confidence",...situation.maneuvers.map(id=>MANEUVERS.find(maneuver=>maneuver.id===id)?.label??id)],control:{label:"Open Campaign",module:"campaign"}}));
  [...DOMESTIC_SUB_MISSIONS,...NETWORK_SUB_MISSIONS].forEach(mission=>{
    const frames=SUB_MISSION_FRAMES.filter(frame=>frame.archetypeId===mission.id),realizations=realizationsForArchetype(mission.id);
    const frameNodeId=(frameId:string)=>`${mission.domain}.${mission.id}.${frameId}`;
    const realizationNodeId=(frameId:string,realizationId:string)=>`${frameNodeId(frameId)}.${realizationId}`;
    const responseLabels=mission.options.map(option=>FAMILIES.find(family=>family.id===option.familyId)?.choices.find(choice=>choice.id===option.choiceId)?.label??option.choiceId);
    const convergenceNodes=mission.convergence.flatMap(edge=>[edge.source,edge.via,edge.target]);
    nodes.push({id:mission.id,label:mission.label,summary:mission.definition,body:`${mission.domain.toUpperCase()} / ${mission.category}. ${frames.length} authored incidents can recur at ${realizations.length} different moments in a campaign, creating ${frames.length*realizations.length} distinct situations. Current pressure determines which problem reaches command; recent history prevents stale repetition.`,related:[...frames.map(frame=>frameNodeId(frame.id)),...responseLabels,...convergenceNodes],control:{label:"Open Campaign",module:"campaign"}});
    frames.forEach(frame=>{
      const frameId=frameNodeId(frame.id),variantIds=realizations.map(realization=>realizationNodeId(frame.id,realization.id));
      nodes.push({id:frameId,label:frame.title,summary:frame.brief,body:`${mission.category}. ${frame.question} Authority: ${frame.authority}. The actor, institution, incident, and command question remain one coherent situation. Live evidence and the current front-line problem determine when it appears.`,related:[mission.id,...variantIds,...responseLabels,...convergenceNodes],control:{label:"Open Campaign",module:"campaign"}});
      realizations.forEach(realization=>nodes.push({id:realizationNodeId(frame.id,realization.id),label:`${frame.title} // ${realization.id}`,summary:`${frame.brief} ${realization.coda}`,body:`Commander question: ${frame.question} ${realization.questionCoda} Authority: ${frame.authority}. Current pressure, live evidence, and the front-line consequence are preserved in today's command docket.`,related:[frameId,mission.id,...responseLabels,...convergenceNodes],control:{label:"Open Campaign",module:"campaign"}}));
    });
  });
  const byId=new Map(nodes.map(node=>[node.id,node])),byLabel=new Map<string,string>();nodes.forEach(node=>{byLabel.set(slug(node.label),node.id);byLabel.set(slug(node.id),node.id)});SUB_MISSION_FRAMES.forEach(frame=>{const id=`${frame.domain}.${frame.archetypeId}.${frame.id}`;frame.aliases.forEach(alias=>byLabel.set(slug(alias),id))});
  const resolve=(label:string)=>byId.has(label)?label:byLabel.get(slug(label));
  nodes.flatMap(node=>node.related).forEach(label=>{if(resolve(label))return;const id=slug(label);if(!id||byId.has(id))return;const placeholder:FieldManualNode={id,label,summary:`Connected campaign concept: ${label}.`,body:"This dependency currently has no independent numerical state; it remains linkable so the graph does not terminate in unexplained text.",related:[]};nodes.push(placeholder);byId.set(id,placeholder);byLabel.set(slug(label),id)});
  const usedBy=new Map<string,string[]>();nodes.forEach(node=>node.related.forEach(label=>{const target=resolve(label);if(target)usedBy.set(target,[...(usedBy.get(target)??[]),node.id])}));
  return{nodes,byId,resolve,usedBy};
};

export const FIELD_MANUAL_CATALOG=buildCatalog();

export function FieldManual({article,variant="command",onControl}:{article:string;variant?:"command"|"briefing";onControl?:(module:string,family?:string)=>void}){
  const catalog=useMemo(()=>FIELD_MANUAL_CATALOG,[]),[active,setActive]=useState(catalog.byId.has(article)?article:catalog.resolve(article)??"resolution"),[query,setQuery]=useState("");
  useEffect(()=>{const target=catalog.byId.has(article)?article:catalog.resolve(article);if(target)setActive(target)},[article,catalog]);
  const node=catalog.byId.get(active)??catalog.nodes[0],visible=catalog.nodes.filter(item=>`${item.label} ${item.id} ${item.summary}`.toLowerCase().includes(query.toLowerCase()));
  const activate=(label:string)=>{const target=catalog.resolve(label);if(target)setActive(target)};
  const control=()=>{if(!node.control)return;if(onControl)onControl(node.control.module,node.control.family);else if(node.control.family)window.dispatchEvent(new CustomEvent("open-family",{detail:node.control.family}));else window.dispatchEvent(new CustomEvent("open-module",{detail:node.control.module}))};
  return <div className={`wiki field-manual ${variant==="briefing"?"modern-field-manual":""}`}><header><span className="eyebrow">DELENDA.QUEST FIELD MANUAL</span><h1>Campaign Wiki</h1><p>Every edge is navigable in both directions: dependencies explain what this item consumes; used-by explains what changes downstream.</p></header><div className="wiki-layout"><aside><input aria-label="Search wiki" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search the field manual"/><h3>CONTENTS // {visible.length}</h3>{visible.map(item=><button className={active===item.id?"active":""} onClick={()=>setActive(item.id)} key={item.id}>{item.label}</button>)}</aside><article id={`wiki-${active}`}><div className="wiki-breadcrumb">FIELD MANUAL &gt; LINKED SYSTEM GRAPH &gt; {node.label.toUpperCase()}</div><h1>{node.label}</h1><p className="wiki-lead">{node.summary}</p><div className="wiki-rule"><b>DEFINITION</b><p>{node.body}</p></div>{node.control&&<button className="wiki-control" onClick={control}>CONTROL // {node.control.label.toUpperCase()} →</button>}<div className="wiki-dependency-columns"><section><h2>Depends on</h2><ul>{node.related.map(label=>{const target=catalog.resolve(label),dependency=target?catalog.byId.get(target):undefined;return <li key={label}><button onClick={()=>activate(label)}>{dependency?.label??label} →</button></li>})}</ul></section><section><h2>Used by</h2><ul>{(catalog.usedBy.get(node.id)??[]).map(id=>{const dependent=catalog.byId.get(id)!;return <li key={id}><button onClick={()=>setActive(id)}>{dependent.label} →</button></li>})}{!(catalog.usedBy.get(node.id)?.length)&&<li><span>No registered downstream consumer.</span></li>}</ul></section></div><footer>LAST VERIFIED // CAMPAIGN RULESET V0.4 // SUB-MISSIONS V3 // LINKED SYSTEM GRAPH</footer></article></div></div>;
}
