import type {
  Gate,
  SituationBlueprintRule,
  SituationTemplate,
  Theater,
} from "./campaign-substrate";

const A: Gate = { op: "always" };
const band = (key: Extract<Gate, { op: "band" }>["key"], ...values: string[]): Gate => ({
  op: "band",
  key,
  values,
});
const fact = (id: string, sector: "target" | "any" = "target"): Gate => ({
  op: "fact",
  id,
  sector,
});
const any = (...gates: Gate[]): Gate => ({ op: "any", gates });
const phase = (...values: Extract<Gate, { op: "phase" }>["values"]): Gate => ({
  op: "phase",
  values,
});
const allTheaters: Theater[] = ["lowland", "ridge", "industrial", "river"];

/*
 * Main Campaign plot spines. These are intentionally state-light: the
 * compiler supplies the sector, terrain, ground, network, supply, and
 * intelligence conditions. The authored record supplies the human problem.
 *
 * Historical plot sources were used as structural prompts, never as copied
 * prose: night-march congestion, stores destroyed immediately before an
 * attack, tape-line assembly, broken barrage timing, armor/infantry separation,
 * machine-gun nests in ruins and quarries, exposed bridges, patrol discovery,
 * urban recovery under fire, and aborted clandestine raids.
 */
export const FUNGIBLE_SITUATION_TEMPLATES: SituationTemplate[] = [
  {
    id: "night-march-congestion",
    theater: "lowland",
    sector: "{sector}",
    headline: "Every Arm of the Offensive Has Entered the Same Road at {sector}",
    briefing: "Infantry columns, armored carriers, gun tractors, drone tenders, ambulances, and ammunition vehicles are converging before first light. The timetable assumes each formation can pass through the others. Enemy long-range fires need only discover the queue.",
    question: "Which arm receives the road before daylight makes the argument visible?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 7,
    quote: "A traffic jam is a concentration the enemy did not have to plan.",
    attribution: "Oren Hale, Movement Control Circular",
    maneuvers: ["route", "network", "reinforce", "interdict", "abandon"],
  },
  {
    id: "burning-store-column",
    theater: "industrial",
    sector: "{sector}",
    headline: "The Battle Stores Are Burning Behind {sector}",
    briefing: "A concealed logistics park has taken a direct hit. Fuel, drone cells, shells, and replacement assemblies are detonating in sequence while the assault echelons wait for loads that no longer exist. The enemy has not yet recognized what it struck.",
    question: "Does the operation preserve surprise, replace its stores, or admit that the timetable has burned?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 5,
    quote: "A reserve of materiel is still a reserve. Fire merely makes the commitment legible.",
    attribution: "Director Sel Veyra, Arsenal Loss Register",
    maneuvers: ["route", "reinforce", "interdict", "network", "abandon"],
  },
  {
    id: "barrage-one-lift-short",
    theater: "lowland",
    sector: "{sector}",
    headline: "One Battery at {sector} Is Firing One Lift Behind the War",
    briefing: "The assault has advanced beyond the registered schedule, but a battery section is still walking fire through the line it believes friendly infantry has not reached. Runners report casualties from both directions. The correction must cross the same broken network that caused the error.",
    question: "Is the assault halted, the battery silenced, or the discrepancy spent as tempo?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 3,
    quote: "Fire arriving late does not become support. It becomes a second enemy.",
    attribution: "Gen. Cassius Drake, Strategic Fires Command",
    maneuvers: ["network", "interdict", "reinforce", "route", "abandon"],
  },
  {
    id: "tape-line-in-mud",
    theater: "ridge",
    sector: "{sector}",
    headline: "The Start Line at {sector} Has Moved During the Night",
    briefing: "Engineers laid the assault tapes under darkness. Shelling, traffic, and saturated ground have displaced enough markers that three battalions now possess three different zero lines. The barrage will begin against only one of them.",
    question: "Which certainty is rebuilt before zero hour?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 4,
    quote: "An army begins where every formation agrees the ground begins.",
    attribution: "Col. Aris Thorne, Assault Geometry",
    maneuvers: ["network", "route", "breach", "reinforce", "abandon"],
  },
  {
    id: "gas-at-headquarters",
    theater: "industrial",
    sector: "{sector}",
    headline: "Headquarters at {sector} Is Commanding Through Masks",
    briefing: "Intermittent chemical contamination has forced the command post into sealed intervals. Signals personnel, liaison officers, drone controllers, and battery representatives remain crowded into the same damaged shelter. Orders are coherent individually and incompatible in combination.",
    question: "Which part of command leaves the shelter first?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 6,
    quote: "A headquarters can survive the shell and still die of accumulation.",
    attribution: "Oren Hale, Command Network Authority",
    maneuvers: ["network", "route", "reinforce", "interdict", "abandon"],
  },
  {
    id: "first-trench-empty",
    theater: "ridge",
    sector: "{sector}",
    headline: "The First Position at {sector} Is Empty and the Second Is Awake",
    briefing: "Forward trenches are abandoned, warm, and imperfectly mined. Movement continues on the reverse slope beyond them. Taking the empty works gains ground, but it may also place the infantry exactly where the enemy registered its defensive fires.",
    question: "How far does the line enter an absence?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 6,
    quote: "Vacant ground may be an invitation written by artillery.",
    attribution: "Ava Moore, Field Pattern 18",
    maneuvers: ["exploit", "interdict", "network", "reinforce", "abandon"],
  },
  {
    id: "snipers-in-ruins",
    theater: "industrial",
    sector: "{sector}",
    headline: "The Ruins at {sector} Have No Front",
    briefing: "Infantry has crossed the nominal objective and entered gardens, collapsed workshops, cellars, and broken walls. Snipers and small teams remain behind the advance without occupying any prepared line. Armor can open passages, but every passage exposes a different room.",
    question: "Is the district cleared, sealed, bypassed, or destroyed around its occupants?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 9,
    quote: "A ruin is terrain that has learned to face every direction.",
    attribution: "Col. Aris Thorne, Urban Passage Notes",
    maneuvers: ["breach", "reinforce", "interdict", "network", "abandon"],
  },
  {
    id: "quarry-strongpoint",
    theater: "ridge",
    sector: "{sector}",
    headline: "The Guns at {sector} Are Firing From Below the Map",
    briefing: "Machine guns and short-range batteries are operating from quarries, drainage cuts, and buried industrial chambers. Observation sees the bursts but not the firing positions. Infantry can hear the weapons from several directions and approach them from none without exposure.",
    question: "Which arm converts sound into a flank?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 8,
    quote: "Defilade is a debt transferred from firepower to infantry.",
    attribution: "Gen. Cassius Drake, Doctrine of Indirect Pressure",
    maneuvers: ["interdict", "breach", "network", "reinforce", "abandon"],
  },
  {
    id: "armor-lost-in-smoke",
    theater: "lowland",
    sector: "{sector}",
    headline: "The Armor at {sector} Has Advanced Beyond Its Infantry",
    briefing: "Smoke and dust concealed the armored formation so completely that it also concealed the infantry it was meant to carry through the position. The vehicles are now fighting strongpoints from the rear while their supporting troops remain pinned at the first belt.",
    question: "Is the armor recalled, reinforced, or spent as an accidental encirclement?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 4,
    quote: "A breakthrough without contact is a formation volunteering to become surrounded.",
    attribution: "Comm. Het Claxton, Armored Coordination Appendix",
    maneuvers: ["reinforce", "network", "breach", "exploit", "abandon"],
  },
  {
    id: "infantry-pinned-beside-armor",
    theater: "industrial",
    sector: "{sector}",
    headline: "The Infantry at {sector} Is Using Armor as Terrain",
    briefing: "A column has been stopped at a constricted road. Infantry shelter beside the vehicles while anti-armor fire walks forward and machine guns close the exits. The tanks can deploy only by leaving the infantry, and the infantry can disperse only by leaving the tanks.",
    question: "Which formation abandons the protection that is fixing it in place?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 3,
    quote: "Cover becomes captivity when the enemy can aim at it.",
    attribution: "Col. Aris Thorne, Combined-Arms Failure Register",
    maneuvers: ["breach", "interdict", "network", "reinforce", "abandon"],
  },
  {
    id: "road-fire-four-sides",
    theater: "industrial",
    sector: "{sector}",
    headline: "Fire at {sector} Is Arriving From Every Direction Except the Road Ahead",
    briefing: "The lead vehicles crossed the junction before concealed teams opened from buildings, drainage cuts, and the rear of the column. Flares and drone markers are multiplying faster than headquarters can classify them. Continuing may escape the ambush or complete it.",
    question: "Where is the front when the column is the perimeter?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 4,
    quote: "An ambush is a temporary border drawn around movement.",
    attribution: "Ava Moore, Contact Reconstruction",
    maneuvers: ["interdict", "network", "breach", "reinforce", "abandon"],
  },
  {
    id: "recovery-under-fire",
    theater: "industrial",
    sector: "{sector}",
    headline: "A Burning Vehicle at {sector} Has Become the Center of the Battle",
    briefing: "A disabled armored vehicle blocks the withdrawal route. Recovery crews can salvage its crew, weapons, and route capacity, but the wreck is visible above the surrounding structures and hostile teams are converging on it. Air and drone support can clear approaches only while identification remains trustworthy.",
    question: "What is recovered when the wreck is also the bait?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 5,
    quote: "Recovery is an attack conducted against the enemy's timetable.",
    attribution: "Comm. Het Claxton, Materiel Recovery Doctrine",
    maneuvers: ["reinforce", "interdict", "network", "route", "abandon"],
  },
  {
    id: "railway-without-support",
    theater: "industrial",
    sector: "{sector}",
    headline: "The Infantry at {sector} Has Reached the Railway Without Its Fires",
    briefing: "Patrols crossed the village and found resistance only at the rail embankment. The batteries cannot acquire the reverse slope, drones lose signal below the cut, and armor cannot traverse the wrecked crossing. The objective is visible from a position that cannot yet attack it.",
    question: "Is the railway the objective, the limit, or the place the operation waits to die?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 7,
    quote: "An unsupported objective is merely a place from which defeat can be observed closely.",
    attribution: "Gen. Cassius Drake, Fires Coordination Memorandum",
    maneuvers: ["interdict", "network", "route", "reinforce", "abandon"],
  },
  {
    id: "pontoon-before-guns",
    theater: "river",
    sector: "{sector}",
    headline: "The Bridge at {sector} Can Carry Infantry or Batteries Before Dawn, Not Both",
    briefing: "Engineers have completed one temporary span and two unfinished approaches. Foot traffic can cross immediately. Heavy artillery requires reinforcement work that will hold the infantry on the near bank until daylight. Enemy observers are already searching the waterline.",
    question: "Which arm arrives first on the far bank, and which arm promises to follow?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 6,
    quote: "A bridge allocates time before it allocates weight.",
    attribution: "Engineer Directorate, River Operations",
    maneuvers: ["route", "reinforce", "interdict", "network", "abandon"],
  },
  {
    id: "battery-on-the-near-bank",
    theater: "river",
    sector: "{sector}",
    headline: "The Assault Has Crossed {sector} and Its Batteries Have Not",
    briefing: "Infantry and drones hold a shallow lodgment beyond the waterline. Counterbattery fire has closed the prepared gun approaches, leaving supporting artillery on the near bank with degrading observation and a growing minimum range problem.",
    question: "Does the lodgment deepen without guns, or do the guns cross under the protection of the lodgment?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 5,
    quote: "The far bank is not held until support can arrive there unwillingly.",
    attribution: "Gen. Cassius Drake, Crossing Fires",
    maneuvers: ["route", "interdict", "reinforce", "network", "abandon"],
  },
  {
    id: "counterbattery-after-displacement",
    theater: "lowland",
    sector: "{sector}",
    headline: "The Enemy Batteries at {sector} Fired, Displaced, and Continued Firing",
    briefing: "Drones retained two launch signatures but lost the vehicles under camouflage. Sound ranging places the new positions beyond the expected displacement radius. Firing now may kill empty ground; waiting allows another complete mission against the line.",
    question: "Which uncertainty receives the counterbattery reserve?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 3,
    quote: "A battery survives by making yesterday's certainty expensive.",
    attribution: "Gen. Cassius Drake, Counterbattery Notes",
    maneuvers: ["interdict", "network", "exploit", "reinforce", "abandon"],
  },
  {
    id: "patrol-feed-disagrees",
    theater: "lowland",
    sector: "{sector}",
    headline: "The Patrol and the Drone at {sector} Have Observed Different Wars",
    briefing: "A ground patrol reports an empty approach and fresh track marks toward the rear. Drone imagery shows occupied firing pits without visible movement. One source may be late, one may be deceived, or both may be accurately describing different layers of the position.",
    question: "Which witness is allowed to move the formation?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 4,
    quote: "Contradictory reports are often two accurate measurements of a moving thing.",
    attribution: "Ava Moore, Pattern Analysis Directorate",
    maneuvers: ["network", "interdict", "exploit", "reinforce", "abandon"],
  },
  {
    id: "cloud-break-over-airfield",
    theater: "lowland",
    sector: "{sector}",
    headline: "A Twelve-Minute Sky Has Opened Above {sector}",
    briefing: "Low cloud has concealed the enemy air echelon and grounded friendly attack flights. A narrow break now exposes aircraft, fuelers, and air-defense radars before either side's published forecast recognizes the window. The strike package is armed for a different target.",
    question: "Is the air plan rewritten faster than the weather can close it?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 2,
    quote: "Weather creates targets by briefly permitting them to exist.",
    attribution: "Air Marshal Yara Sol, Unscheduled Windows",
    maneuvers: ["exploit", "interdict", "network", "reinforce", "abandon"],
  },
  {
    id: "air-cover-beyond-radius",
    theater: "river",
    sector: "{sector}",
    headline: "The Advance at {sector} Has Outrun Its Air Umbrella",
    briefing: "Forward infantry and armor are moving beyond the reliable identification and fuel radius of friendly air cover. Enemy aircraft remain intermittent but unopposed at the edge of the corridor. Halting preserves the umbrella and surrenders the tempo.",
    question: "How much ground is worth becoming unrecognizable from the air?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 6,
    quote: "Air superiority has a border measured in minutes.",
    attribution: "Air Marshal Yara Sol, Radius Doctrine",
    maneuvers: ["network", "reinforce", "interdict", "exploit", "abandon"],
  },
  {
    id: "battery-breaks-fire-plan",
    theater: "ridge",
    sector: "{sector}",
    headline: "The Battery at {sector} Must Displace During Its Own Fire Plan",
    briefing: "Counterbattery acquisition arrived sooner than predicted. The guns can complete the suppression sequence and risk destruction, displace now and open a gap over the assault, or hand the mission to a battery whose ammunition and angles were calculated for another sector.",
    question: "Which failure remains supportable: silence, exposure, or substitution?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 3,
    quote: "A fire plan is a promise made by weapons the enemy is also scheduling.",
    attribution: "Gen. Cassius Drake, Strategic Fires Command",
    maneuvers: ["interdict", "route", "network", "reinforce", "abandon"],
  },
  {
    id: "armor-gap-in-rubble",
    theater: "industrial",
    sector: "{sector}",
    headline: "One Vehicle Can Pass the Rubble at {sector}",
    briefing: "Engineers have opened a lane wide enough for a single armored vehicle at a time. Infantry can expand the breach under direct fire, armor can force through without lateral support, or drones can hold observation while the route is rebuilt. The enemy is moving reserves toward the choke point.",
    question: "Is the narrow passage used before it becomes safe?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 5,
    quote: "A gap becomes a route only after the enemy has had time to aim at it.",
    attribution: "Col. Aris Thorne, Forced Passage",
    maneuvers: ["breach", "exploit", "interdict", "reinforce", "abandon"],
  },
  {
    id: "drone-relay-last-charge",
    theater: "ridge",
    sector: "{sector}",
    headline: "The Relay Drone Above {sector} Has One Rotation Remaining",
    briefing: "The airborne relay is sustaining infantry position reports, battery correction, and armored identification across masked terrain. Its replacement cannot reach station before the current platform exhausts its cells. Every supported arm claims continuity is decisive.",
    question: "Which conversation survives the last charge?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 4,
    quote: "A network fails one priority at a time before it fails all at once.",
    attribution: "Oren Hale, Relay Custody",
    maneuvers: ["network", "interdict", "reinforce", "route", "abandon"],
  },
  {
    id: "ammunition-road-priority",
    theater: "lowland",
    sector: "{sector}",
    headline: "The Road to {sector} Can Carry Shells or Replacements",
    briefing: "A damaged approach has been restored to one-way movement. Artillery ammunition is queued behind personnel carriers and recovery vehicles returning empty. The front can receive volume of fire, fresh infantry, or repaired armor before the enemy pressure cycle resumes.",
    question: "Which shortage is permitted to arrive second?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 8,
    quote: "Logistics is the authority to decide which necessity becomes late.",
    attribution: "Comm. Het Claxton, Operational Depth Memorandum",
    maneuvers: ["route", "reinforce", "interdict", "network", "abandon"],
  },
  {
    id: "shell-hole-infiltration",
    theater: "lowland",
    sector: "{sector}",
    headline: "Enemy Infantry Is Crossing {sector} Without Forming a Line",
    briefing: "Small groups are moving through shell holes, drainage cuts, and dead ground between fixed posts. Artillery has no concentration to strike, drones lose individuals in the clutter, and local infantry can contain only what it first allows to approach.",
    question: "At what scale does infiltration become an attack?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 7,
    quote: "A line is penetrated long before headquarters agrees that anything crossed it.",
    attribution: "Ava Moore, Accumulation Warning",
    maneuvers: ["reinforce", "interdict", "network", "breach", "abandon"],
  },
  {
    id: "breakfast-still-warm",
    theater: "lowland",
    sector: "{sector}",
    headline: "The Enemy Left Breakfast at {sector}",
    briefing: "Patrols have entered forward positions without contact. Food remains warm, field telephones remain connected, and several heavy weapons are missing rather than abandoned. The withdrawal may be hurried, theatrical, or only one line deep.",
    question: "What follows an enemy who intended to be followed?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 5,
    quote: "Haste leaves evidence. Deception leaves evidence selected for you.",
    attribution: "Ava Moore, Withdrawal Analysis",
    maneuvers: ["exploit", "interdict", "network", "reinforce", "abandon"],
  },
  {
    id: "isolated-strongpoint",
    theater: "ridge",
    sector: "{sector}",
    headline: "The Strongpoint at {sector} Has Been Passed and Has Not Stopped Firing",
    briefing: "The advance moved around a fortified position that now sits behind the leading infantry. Its garrison can interdict supply, report movement, or surrender after the decisive hour. Turning back spends tempo; continuing converts the strongpoint into a rear-area battle.",
    question: "When does bypassed resistance become an encirclement of the bypasser?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 7,
    quote: "A position behind you is not behind the war.",
    attribution: "Col. Aris Thorne, Strongpoint Reduction",
    maneuvers: ["breach", "interdict", "reinforce", "network", "abandon"],
  },
  {
    id: "casualty-station-in-axis",
    theater: "industrial",
    sector: "{sector}",
    headline: "The Evacuation Station at {sector} Occupies the Only Covered Approach",
    briefing: "The route selected for the next assault is already carrying wounded, ambulances, and replacement medical stores. Moving the station exposes casualties. Leaving it blocks armored passage and advertises the attack axis through the volume of preparation.",
    question: "Which body of evidence is moved first: the wounded or the offensive?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 8,
    quote: "An evacuation route is a road whose direction has become moral.",
    attribution: "Comm. Het Claxton, Casualty Expenditure Appendix",
    maneuvers: ["route", "reinforce", "network", "interdict", "abandon"],
  },
  {
    id: "demolition-raid-aborts",
    theater: "river",
    sector: "{sector}",
    headline: "The Raid on {sector} Failed Before Reaching the Shore",
    briefing: "A clandestine demolition team is holding offshore after propulsion failure and signs of an alerted landing area. The target remains vulnerable, but surprise may already be gone. Air and artillery diversions can reopen the approach while also confirming the objective.",
    question: "Is secrecy preserved by withdrawal or recovered through violence?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 4,
    quote: "A raid begins to fail when the target starts making decisions about it.",
    attribution: "Special Operations File, Littoral Entry",
    maneuvers: ["network", "interdict", "route", "exploit", "abandon"],
  },
  {
    id: "rail-cut-behind-column",
    theater: "industrial",
    sector: "{sector}",
    headline: "The Enemy Column at {sector} Has Passed the Point Where Its Rail Line Can Be Cut",
    briefing: "A small demolition force can sever the route behind the moving formation, trapping its supply and delaying reinforcement. The same charge will reveal the infiltrators and may close the only usable rail bed for a friendly advance.",
    question: "Is the route destroyed because the enemy used it first?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 5,
    quote: "Sabotage is ownership exercised for one explosion.",
    attribution: "Special Operations File, Rail Interdiction",
    maneuvers: ["interdict", "exploit", "network", "reinforce", "abandon"],
  },
  {
    id: "rolling-barrage-outpaces-line",
    theater: "lowland",
    sector: "{sector}",
    headline: "The Barrage at {sector} Has Left the Infantry Behind",
    briefing: "Mud, wire, and casualties have slowed the assault while the fire plan continues on schedule. The enemy is emerging into the widening interval. Batteries can repeat old lifts, armor can cross the infantry, or the line can advance without the protection it was promised.",
    question: "Which clock is permitted to become wrong?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 3,
    quote: "A barrage protects only the soldiers who inhabit its timetable.",
    attribution: "Gen. Cassius Drake, Assault Fires",
    maneuvers: ["interdict", "breach", "network", "reinforce", "abandon"],
  },
  {
    id: "drone-swarm-without-corridor",
    theater: "industrial",
    sector: "{sector}",
    headline: "The Drone Swarm at {sector} Has Targets and No Safe Return Corridor",
    briefing: "The swarm has classified enemy armor and battery vehicles beyond the line, but air defenses have closed the planned recovery lane. Spending the platforms may complete the strike. Re-tasking them as relays or decoys preserves the ground force and abandons the machines.",
    question: "Which capability is more valuable than the airframes carrying it?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 3,
    quote: "A reusable machine becomes expendable at the moment return costs the mission.",
    attribution: "Dr. Anika Sorell, Drone Systems Memorandum",
    maneuvers: ["interdict", "network", "exploit", "reinforce", "abandon"],
  },
  {
    id: "friendly-identification-collapse",
    theater: "industrial",
    sector: "{sector}",
    headline: "Airpower at {sector} Can Find the Enemy but Not the Friendly Line",
    briefing: "Smoke, displaced units, and relay loss have erased the current boundary from the air picture. Attack flights retain weapons and targets. Ground commanders can mark positions with emissions the enemy will also see, or accept that air support has become a threat held in reserve.",
    question: "How much of the line is exposed in order to distinguish it?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 4,
    quote: "Identification is the permission structure of fire.",
    attribution: "Air Marshal Yara Sol, Fratricide Prevention Order",
    maneuvers: ["network", "interdict", "reinforce", "route", "abandon"],
  },
  {
    id: "wire-party-brings-prisoner",
    theater: "ridge",
    sector: "{sector}",
    headline: "The Wire Party at {sector} Returned With an Enemy Runner",
    briefing: "Infantry sent to repair the forward obstacle dragged back a signals runner, a satchel of authentication cards, and a warning that enemy patrols now use the gaps cut for friendly movement. The cards may open the enemy net once. The wire can be closed once. Both opportunities expire before daylight.",
    question: "Is the captured access spent on intelligence, deception, or the immediate survival of the obstacle line?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 4,
    quote: "A prisoner sometimes carries the door he was sent through.",
    attribution: "Oren Hale, Authentication Casualties",
    maneuvers: ["network", "interdict", "reinforce", "route", "abandon"],
  },
  {
    id: "disabled-armor-as-observation",
    theater: "lowland",
    sector: "{sector}",
    headline: "The Disabled Armor at {sector} Can See What Headquarters Cannot",
    briefing: "Three immobilized vehicles remain inside the forward engagement area. Their weapons are limited, their optics are intact, and their crews can classify the enemy reserve route from ground no observer can reach on foot. Recovery, remote observation, and a final direct-fire mission require the same remaining battery power.",
    question: "What does the formation become after it can no longer move?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 5,
    quote: "Mobility lost is not usefulness lost until command insists they are synonyms.",
    attribution: "Maj. Ilyan Rook, Armored Recovery Notes",
    maneuvers: ["interdict", "network", "reinforce", "route", "abandon"],
  },
  {
    id: "battery-fires-drone-grid",
    theater: "industrial",
    sector: "{sector}",
    headline: "The Battery at {sector} Is Firing a Grid Written by Drones",
    briefing: "The artillery observers are cut off, but drone teams continue passing target grids through a civilian relay. The coordinates are fast, precise, and unauthenticated. Enemy jamming has already inserted one false vehicle column into the feed.",
    question: "How much fire is entrusted to a picture nobody can certify?",
    terrain: "Compiled from sector",
    ground: "Compiled from sector",
    network: "Compiled from sector",
    supply: "Compiled from sector",
    intelligence: "Compiled from state",
    windowHours: 3,
    quote: "Precision without provenance is merely error delivered accurately.",
    attribution: "Gen. Cassius Drake, Remote Fires Inquiry",
    maneuvers: ["interdict", "network", "reinforce", "breach", "abandon"],
  },
];

export const FUNGIBLE_BLUEPRINT_RULES: Record<string, SituationBlueprintRule> = {
  "night-march-congestion": { id: "night-march-congestion", problemClass: "logistics", theaters: allTheaters, requires: A, targetSelector: "lowest-supply", baseUrgency: 57, cooldown: 6, standingOrder: "Movement continues by existing priority until daylight exposes the queue." },
  "burning-store-column": { id: "burning-store-column", problemClass: "logistics", theaters: ["lowland", "industrial", "river"], requires: A, targetSelector: "most-damaged", baseUrgency: 54, cooldown: 7, standingOrder: "The operation proceeds against the loads already distributed." },
  "barrage-one-lift-short": { id: "barrage-one-lift-short", problemClass: "command", theaters: allTheaters, requires: any(band("network", "severed", "degraded", "intermittent"), phase("compression", "exhaustion", "terminal")), targetSelector: "weakest-network", baseUrgency: 62, cooldown: 6, standingOrder: "The published fire plan continues until a correction reaches every battery." },
  "tape-line-in-mud": { id: "tape-line-in-mud", problemClass: "command", theaters: ["lowland", "ridge", "river"], requires: A, targetSelector: "frontline", baseUrgency: 51, cooldown: 7, standingOrder: "Formations assemble on the last confirmed line." },
  "gas-at-headquarters": { id: "gas-at-headquarters", problemClass: "command", theaters: allTheaters, requires: any(band("network", "severed", "degraded"), phase("exhaustion", "terminal")), targetSelector: "weakest-network", baseUrgency: 58, cooldown: 7, standingOrder: "The crowded command post continues transmitting through sealed intervals." },
  "first-trench-empty": { id: "first-trench-empty", problemClass: "observation", theaters: ["lowland", "ridge", "industrial"], requires: A, targetSelector: "highest-pressure", baseUrgency: 55, cooldown: 6, standingOrder: "Patrols hold the first empty position and do not enter the reverse slope." },
  "snipers-in-ruins": { id: "snipers-in-ruins", problemClass: "assault", theaters: ["industrial", "lowland"], requires: A, targetSelector: "most-damaged", baseUrgency: 60, cooldown: 6, standingOrder: "The district is contained while isolated fire continues behind the advance." },
  "quarry-strongpoint": { id: "quarry-strongpoint", problemClass: "assault", theaters: ["ridge", "industrial"], requires: A, targetSelector: "highest-pressure", baseUrgency: 59, cooldown: 6, standingOrder: "The hidden strongpoint remains under observation and intermittent suppression." },
  "armor-lost-in-smoke": { id: "armor-lost-in-smoke", problemClass: "exploitation", theaters: allTheaters, requires: A, targetSelector: "frontline", baseUrgency: 56, cooldown: 6, standingOrder: "The armored formation holds its accidental lodgment until contact is restored." },
  "infantry-pinned-beside-armor": { id: "infantry-pinned-beside-armor", problemClass: "force-preservation", theaters: ["industrial", "lowland", "river"], requires: A, targetSelector: "most-damaged", baseUrgency: 61, cooldown: 6, standingOrder: "The column remains fixed around its armored cover." },
  "road-fire-four-sides": { id: "road-fire-four-sides", problemClass: "counterstroke", theaters: ["industrial", "lowland"], requires: A, targetSelector: "highest-pressure", baseUrgency: 63, cooldown: 7, standingOrder: "The column fights in place while the direction of the attack is reconstructed." },
  "recovery-under-fire": { id: "recovery-under-fire", problemClass: "force-preservation", theaters: ["industrial", "lowland", "river"], requires: A, targetSelector: "most-damaged", baseUrgency: 55, cooldown: 7, standingOrder: "The wreck remains in place and the withdrawal route remains constricted." },
  "railway-without-support": { id: "railway-without-support", problemClass: "logistics", theaters: ["industrial", "lowland"], requires: A, targetSelector: "lowest-supply", baseUrgency: 58, cooldown: 6, standingOrder: "The infantry holds short of the railway until support can acquire the reverse slope." },
  "pontoon-before-guns": { id: "pontoon-before-guns", problemClass: "crossing", theaters: ["river"], requires: A, targetSelector: "most-damaged", baseUrgency: 64, cooldown: 6, standingOrder: "Foot traffic crosses while the heavy approaches remain incomplete." },
  "battery-on-the-near-bank": { id: "battery-on-the-near-bank", problemClass: "crossing", theaters: ["river"], requires: A, targetSelector: "highest-pressure", baseUrgency: 61, cooldown: 6, standingOrder: "The lodgment remains supported from degrading positions on the near bank." },
  "counterbattery-after-displacement": { id: "counterbattery-after-displacement", problemClass: "observation", theaters: allTheaters, requires: any(fact("enemy_fires_registered", "any"), phase("compression", "exhaustion", "terminal")), targetSelector: "highest-pressure", baseUrgency: 58, cooldown: 6, standingOrder: "Counterbattery sections retain the last confirmed coordinates." },
  "patrol-feed-disagrees": { id: "patrol-feed-disagrees", problemClass: "observation", theaters: allTheaters, requires: A, targetSelector: "frontline", baseUrgency: 52, cooldown: 6, standingOrder: "Movement remains suspended at the last mutually confirmed position." },
  "cloud-break-over-airfield": { id: "cloud-break-over-airfield", problemClass: "exploitation", theaters: ["lowland", "industrial", "river"], requires: A, targetSelector: "highest-pressure", baseUrgency: 49, cooldown: 8, standingOrder: "The armed flights continue toward their assigned target." },
  "air-cover-beyond-radius": { id: "air-cover-beyond-radius", problemClass: "force-preservation", theaters: allTheaters, requires: any(band("frontPosture", "advancing", "breakthrough"), phase("compression", "exhaustion", "terminal")), targetSelector: "frontline", baseUrgency: 57, cooldown: 7, standingOrder: "The advance continues to the edge of reliable air identification." },
  "battery-breaks-fire-plan": { id: "battery-breaks-fire-plan", problemClass: "assault", theaters: allTheaters, requires: A, targetSelector: "highest-pressure", baseUrgency: 60, cooldown: 6, standingOrder: "The battery completes its published mission before displacement." },
  "armor-gap-in-rubble": { id: "armor-gap-in-rubble", problemClass: "exploitation", theaters: ["industrial", "ridge", "lowland"], requires: A, targetSelector: "most-damaged", baseUrgency: 57, cooldown: 6, standingOrder: "The narrow passage remains unused while engineers widen it." },
  "drone-relay-last-charge": { id: "drone-relay-last-charge", problemClass: "command", theaters: allTheaters, requires: A, targetSelector: "weakest-network", baseUrgency: 55, cooldown: 6, standingOrder: "The relay continues serving every channel until power exhaustion." },
  "ammunition-road-priority": { id: "ammunition-road-priority", problemClass: "logistics", theaters: allTheaters, requires: any(band("supply", "famine", "critical", "strained"), phase("compression", "exhaustion", "terminal")), targetSelector: "lowest-supply", baseUrgency: 61, cooldown: 6, standingOrder: "Existing road priority remains in force." },
  "shell-hole-infiltration": { id: "shell-hole-infiltration", problemClass: "counterstroke", theaters: ["lowland", "ridge", "river"], requires: A, targetSelector: "highest-pressure", baseUrgency: 60, cooldown: 6, standingOrder: "Local posts contain only the infiltrators they can confirm." },
  "breakfast-still-warm": { id: "breakfast-still-warm", problemClass: "exploitation", theaters: ["lowland", "ridge", "industrial"], requires: A, targetSelector: "frontline", baseUrgency: 53, cooldown: 7, standingOrder: "Patrols retain the abandoned forward position without pursuing." },
  "isolated-strongpoint": { id: "isolated-strongpoint", problemClass: "assault", theaters: allTheaters, requires: A, targetSelector: "highest-pressure", baseUrgency: 58, cooldown: 6, standingOrder: "The bypassed position remains screened by the minimum available force." },
  "casualty-station-in-axis": { id: "casualty-station-in-axis", problemClass: "logistics", theaters: allTheaters, requires: A, targetSelector: "lowest-supply", baseUrgency: 50, cooldown: 8, standingOrder: "Evacuation traffic retains priority over offensive movement." },
  "demolition-raid-aborts": { id: "demolition-raid-aborts", problemClass: "observation", theaters: ["river", "industrial"], requires: A, targetSelector: "weakest-network", baseUrgency: 48, cooldown: 8, standingOrder: "The raiding force withdraws without confirming whether it was detected." },
  "rail-cut-behind-column": { id: "rail-cut-behind-column", problemClass: "exploitation", theaters: ["industrial", "lowland"], requires: A, targetSelector: "lowest-supply", baseUrgency: 55, cooldown: 7, standingOrder: "The demolition force remains concealed and the rail line remains open." },
  "rolling-barrage-outpaces-line": { id: "rolling-barrage-outpaces-line", problemClass: "assault", theaters: ["lowland", "ridge", "industrial"], requires: any(phase("compression", "exhaustion", "terminal"), band("frontPosture", "advancing", "breakthrough")), targetSelector: "frontline", baseUrgency: 62, cooldown: 6, standingOrder: "The infantry continues toward the published barrage line." },
  "drone-swarm-without-corridor": { id: "drone-swarm-without-corridor", problemClass: "exploitation", theaters: allTheaters, requires: A, targetSelector: "highest-pressure", baseUrgency: 52, cooldown: 7, standingOrder: "The swarm holds outside the closed recovery corridor." },
  "friendly-identification-collapse": { id: "friendly-identification-collapse", problemClass: "command", theaters: allTheaters, requires: any(band("network", "severed", "degraded"), band("intelligence", "blind", "contradictory")), targetSelector: "weakest-network", baseUrgency: 61, cooldown: 7, standingOrder: "Attack aircraft remain armed but outside the contested identification zone." },
  "wire-party-brings-prisoner": { id: "wire-party-brings-prisoner", problemClass: "observation", theaters: allTheaters, requires: A, targetSelector: "frontline", baseUrgency: 52, cooldown: 7, standingOrder: "The captured authentication remains unspent while the obstacle party closes the nearest gap.", writingOnly:true },
  "disabled-armor-as-observation": { id: "disabled-armor-as-observation", problemClass: "force-preservation", theaters: allTheaters, requires: A, targetSelector: "most-damaged", baseUrgency: 54, cooldown: 7, standingOrder: "The disabled vehicles remain concealed and report only confirmed movement.", writingOnly:true },
  "battery-fires-drone-grid": { id: "battery-fires-drone-grid", problemClass: "command", theaters: allTheaters, requires: A, targetSelector: "weakest-network", baseUrgency: 56, cooldown: 7, standingOrder: "The battery retains its last authenticated fire mission.", writingOnly:true },
};
