export type OpportunityCategory =
  | "individual-action"
  | "clandestine-sabotage"
  | "proxy-warfare"
  | "equipment-recovery"
  | "energy-warfare"
  | "political-warfare"
  | "leadership-interdiction"
  | "counterintelligence"
  | "personnel-recovery"
  | "domestic-reform";

export type OpportunitySpine = {
  id:string;
  category:OpportunityCategory;
  sourceSpine:string;
  label:string;
  individual:string;
  headline:string;
  brief:string;
  primary:string;
  alternate:string;
};

export const OPPORTUNITY_CATEGORY_LABELS:Record<OpportunityCategory,string>={
  "individual-action":"Individual Initiative",
  "clandestine-sabotage":"Clandestine Sabotage",
  "proxy-warfare":"Proxy Warfare",
  "equipment-recovery":"Materiel Capture",
  "energy-warfare":"Energy Warfare",
  "political-warfare":"Political Warfare",
  "leadership-interdiction":"Leadership Interdiction",
  "counterintelligence":"Counterintelligence",
  "personnel-recovery":"Personnel Recovery",
  "domestic-reform":"War Department Reform",
};

export const OPPORTUNITY_RESEARCH_SOURCES=[
  {id:"soe",title:"Imperial War Museums // SOE and resistance operations",url:"https://www.iwm.org.uk/history/second-world-war/intelligence/seven-stories-from-special-operations-executive"},
  {id:"resistance",title:"Imperial War Museums // Spies, Saboteurs and D-Day",url:"https://www.iwm.org.uk/history/second-world-war/d-day/spies-saboteurs-and-d-day"},
  {id:"special-operations",title:"U.S. Army history // Special Operations in World War II",url:"https://history.army.mil/portals/143/Images/Publications/catalog/70-42.pdf"},
  {id:"small-unit",title:"U.S. Army history // Small Unit Actions",url:"https://history.army.mil/portals/143/Images/Publications/catalog/100-14.pdf"},
  {id:"lrrp",title:"Army University Press // Eyes Behind the Lines",url:"https://www.armyupress.army.mil/Portals/7/combat-studies-institute/csi-books/gebhardt_LRRP.pdf"},
  {id:"oral-history",title:"Army University Press // Eyewitness to War oral histories",url:"https://www.armyupress.army.mil/Portals/7/Primer-on-Urban-Operation/Documents/EyewitnessToWar_VolumeI.pdf"},
  {id:"naval-special-operations",title:"Naval History and Heritage Command // Special Operations in Korea",url:"https://www.history.navy.mil/research/library/online-reading-room/title-list-alphabetically/u/usnavy-special-operations-korean-war.html"},
] as const;

type Row=readonly [id:string,label:string,individual:string,headline:string,brief:string,primary:string,alternate:string];
const group=(category:OpportunityCategory,sourceSpine:string,rows:readonly Row[]):OpportunitySpine[]=>rows.map(([id,label,individual,headline,brief,primary,alternate])=>({id,category,sourceSpine,label,individual,headline,brief,primary,alternate}));

// These are original fictional composites. Historical sources supply mission spines and material
// texture, never copied characters, quotations, unit identities, or outcomes.
export const OPPORTUNITY_SPINES:OpportunitySpine[]=[
  ...group("individual-action","small-unit // oral-history",[
    ["culvert-listener","The Culvert Listener","A signals corporal with a field receiver","A Corps Net Is Leaking Through a Drainage Culvert","A corporal sheltering beneath a road hears an enemy retransmission bounce through buried telephone cable. The signal is clean only while the rain keeps both patrols under cover.","Tap the Buried Pair","Shadow the Relay Team"],
    ["tram-spotter","The Tram Spotter","A municipal tram conductor attached as a guide","The Last Tram Has Counted Every Gun on the Avenue","A conductor notices that each enemy gun crew halts traffic with a different hand signal. From the rear platform she has reconstructed the entire battery sequence without leaving her route.","Transmit the Firing Sequence","Ride One More Circuit"],
    ["medic-courtyard","The Courtyard Medic","A battalion medic carrying two wounded surveyors","The Wounded Surveyors Still Have the Enemy Grid","A medic reaches two surveyors in a courtyard cut off by fire. Their maps identify a command post that will relocate as soon as the men are searched.","Extract the Surveyors","Send the Grid Without Them"],
    ["tanker-service-lane","The Service-Lane Tanker","A disabled tank commander with one working optic","A Disabled Tank Can See the Reserve Assembly Area","The commander's transmission is gone, but a narrow service lane gives his remaining optic an uninterrupted view of enemy reserves forming behind warehouses.","Use the Tank as an Observation Post","Recover the Optic and Crew"],
    ["sapper-unfired-ring","The Unfired Ring","A sapper inspecting an abandoned demolition site","The Enemy Left Its Bridge Charges Unfired","A sapper finds a complete demolition ring under the east bridge. The firing wire runs into hostile ground, but the charges and their placement remain intact.","Reverse the Demolition Circuit","Lift the Charges for Reuse"],
    ["weather-clerk","The Weather Clerk's Window","A weather clerk with access to balloon reports","A Twelve-Minute Cloud Break Crosses the Enemy Airfield","The clerk sees a gap no operations staff has requested. It will expose aircraft parked outside revetments before the next forecast is formally issued.","Release the Unscheduled Strike Window","Track the Dispersal Response"],
    ["railwayman-chalk","Chalk Marks at Junction Nine","A railwayman conscripted into transport control","Three Chalk Marks Identify the Ammunition Train","The railwayman recognizes a private yard code on cars entered as agricultural freight. The consist will split at the next junction and become indistinguishable.","Divert the Ammunition Cars","Tag Both Successor Trains"],
    ["telephone-girl","The Switchboard Hold","A telephone exchange operator who refused evacuation","The Enemy Staff Is Still Using a Civilian Switchboard","An operator has kept two headquarters callers waiting on separate lines. Joining them would expose the command relationship, but the exchange may be traced immediately.","Bridge the Two Calls","Record the Calling Pattern"],
    ["drone-repairer","The Repairer's False Return","A drone repairer with a captured transponder","A Broken Reconnaissance Drone Still Knows How to Go Home","The airframe cannot fly a mission, but its transponder still authenticates to an enemy recovery beacon that has begun calling it back.","Answer the Recovery Beacon","Clone the Authentication Burst"],
    ["undertaker-route","The Undertaker's Route","A burial detail driver moving between sectors","The Burial Route Bypasses Every Enemy Checkpoint","A driver has been waved through six checkpoints because both armies recognize the cart. Tonight the return compartment is empty and the eastern command archive is moving.","Insert a Two-Person Reconnaissance Team","Map the Checkpoint Rotation"],
  ]),
  ...group("clandestine-sabotage","soe // resistance // naval-special-operations",[
    ["troyes-roundhouse","The Roundhouse Night Shift","A locomotive fitter retained by the occupation authority","Six Locomotives Share One Inspection Pit","A fitter can disable six engines with damage that will resemble a lubrication failure. The night foreman is absent for exactly one inspection cycle.","Cripple the Main Bearings","Contaminate the Repair Inventory"],
    ["lockkeeper-spillway","The Lockkeeper's Key","A lockkeeper whose family lives above the canal office","The Military Canal Can Be Emptied Between Convoys","The lockkeeper has both gate keys and knows the patrol gap. Opening the waste sluice will strand the next fuel barges without flooding the workers' quarter.","Open the Waste Sluice","Alter the Depth Gauges"],
    ["repeater-coal-box","The Coal-Box Repeater","A linesman maintaining a mountain telephone route","The Army Repeater Is Hidden Inside a Coal Box","A linesman confirms that three corps circuits share one disguised repeater. Its backup battery is being replaced at noon under a two-man guard.","Burn the Repeater Cabinet","Substitute a Faulty Battery Bank"],
    ["nitration-batch","The Wrong Nitration Batch","A chemist supervising propellant quality","One Number Can Condemn a Week of Propellant","A chemist can shift the acidity record just far enough to force safe disposal of a full batch. A larger alteration would expose the laboratory.","Spoil the Stabilizer Ratio","Trigger a Plant-Wide Retest"],
    ["ferry-governor","The Ferry Governor","A marine engineer repairing the only heavy ferry","The Ferry's Governor Can Fail Under Load","The engineer can make the propulsion governor seize only when armor boards. The sabotage will leave civilian crossings unaffected until then.","Set the Load-Triggered Failure","Misalign the Vehicle Deck"],
    ["yard-clerk-red-card","The Red Routing Card","A freight clerk with one blank priority card","A Single Card Can Send the Siege Train West","The clerk can place one authenticated routing card before the military dispatcher returns. The wrong junction adds two days and crosses a partisan district.","Reroute the Siege Train","Split Its Escort from the Cargo"],
    ["mine-cage-brake","The Mine-Cage Brake","An electrician in an occupied tungsten mine","The Hoist Brake Has One Uninspected Relay","An electrician can stop the deep cage below the loading gallery without trapping the miners. Replacement components exist only across the front.","Fuse the Brake Relay Open","Destroy the Hoist Control Drawings"],
    ["harbor-clock","The Harbor Clock","A harbor pilot responsible for blackout timing","The Boom Opens by a Clock That Runs Fast","The pilot has measured a seven-minute error between the harbor clock and the patrol launch. A demolition boat can cross before either crew realizes the schedules disagree.","Send the Demolition Boat","Cut the Boom-Control Cable"],
    ["printing-press-gears","The Press with Soft Gears","A typesetter inside the military forms office","Every Movement Order Uses One Numbering Press","The typesetter knows the press has replacement gears made from soft metal. One abrasive paste charge will halt authenticated movement orders for a day.","Grind the Numbering Gears","Steal the Unused Serial Blocks"],
    ["snowplow-pins","The Snowplow Shear Pins","A road mechanic assigned to the mountain pass","The Pass Depends on Two Unmarked Snowplows","The mechanic can substitute brittle shear pins before the forecast storm. The vehicles will fail at the first buried drift, beyond recovery range.","Substitute the Brittle Pins","Drain the Heated Fuel Reservoirs"],
  ]),
  ...group("proxy-warfare","resistance // special-operations",[
    ["schoolmaster-cells","The Schoolmaster's Attendance Book","A schoolmaster coordinating three village couriers","An Attendance Book Is Actually a Cell Map","The absences identify families willing to move messages, medicine, and fugitives. The schoolmaster asks for radios and a promise that his network will not be ordered into open battle.","Cultivate the Courier Network","Arm a Three-Village Auxiliary"],
    ["smugglers-tide","The Smugglers' Tide Table","A boat captain who moves contraband through tidal marshes","Seven Smuggling Boats Can Become a Coastal Screen","The captains already evade both customs services. Fuel and recognition signals would let them watch the enemy coast without placing uniformed patrols there.","Contract the Coastal Screen","Sponsor Maritime Raiding Cells"],
    ["quarrymen-charges","The Quarrymen's Magazine","A blasting foreman with a loyal night crew","The Quarry Crew Knows Every Road-Cut Failure Point","The crew offers to collapse military roads if families receive evacuation papers. Their blasting powder is legal, local, and untraceable to the army.","Sponsor the Road-Denial Cell","Train the Crew as a Demolition Auxiliary"],
    ["dockers-slowdown","The Dockers' Whistle","A union caller who controls shift changes","One Whistle Can Stop the Occupied Port Without a Strike","The caller can create rolling safety stoppages that never become a single prosecutable action. The method needs cash, lawyers, and disciplined timing rather than weapons.","Finance the Rolling Slowdown","Build a Port Intelligence Cell"],
    ["border-shepherds","The Shepherds' Boundary Stones","A herdswoman who crosses the disputed ridge weekly","The Border Patrol Ignores the Only People Who Know Its Route","The shepherd families can report patrol changes and guide small parties across the ridge. They refuse uniforms and central command.","Cultivate the Ridge Guides","Establish a Clandestine Supply Line"],
    ["diaspora-radio","The Exile Radio Hour","A displaced broadcaster with a trusted regional audience","A Popular Music Program Can Carry Mobilization Signals","The broadcaster can embed timing phrases inside requests and dedications. The audience is broad enough to conceal a sponsored insurgency if the code remains sparse.","Open the Coded Broadcast Channel","Recruit a Political Resistance Network"],
    ["dismissed-police","The Dismissed Detectives","A former police inspector with twelve unemployed officers","The Occupation Purged the Only People Who Know the Informants","The dismissed officers retain case notes, habits, and family connections. They will work as a counter-network if promised civilian authority after the war.","Raise a Counterintelligence Auxiliary","Sponsor an Urban Insurgency Cell"],
    ["mountain-club","The Mountaineers' Rescue Club","A climbing instructor whose club spans both sides of the front","A Rescue Club Already Possesses the Skills of a Partisan Unit","Members maintain huts, caches, route cards, and a culture of silent mutual aid. The instructor will support reconnaissance but rejects assassination work.","Cultivate a Reconnaissance Auxiliary","Convert the Huts into Escape Stations"],
    ["refugee-post","The Refugee Post","A midwife moving between reception camps","The Camp Mail Route Crosses Every Security Perimeter","The midwife's assistants carry letters, vaccination cards, and names through places intelligence officers cannot enter. A small stipend could formalize the network without militarizing it.","Fund the Refugee Courier Chain","Use the Chain to Map Collaborator Recruitment"],
    ["prison-break-veterans","The Men from Quarry Prison","An escaped sergeant speaking for twenty former prisoners","Twenty Escapees Ask for a Mission Instead of Evacuation","They know the prison guards, the quarry railway, and the hills where search parties stop. Arming them creates a durable proxy force and a permanent political claimant.","Sponsor the Quarry Insurgency","Task Them with Prisoner Exfiltration"],
  ]),
  ...group("equipment-recovery","small-unit // oral-history",[
    ["bridging-train","The Abandoned Bridging Train","A reconnaissance driver beside an intact engineering convoy","An Enemy Bridging Train Was Left with Its Engines Running","The crews fled an air alarm and have not returned. The vehicles carry pontoons, trestles, and a complete mobile workshop needed at the river sector.","Capture the Bridging Train","Strip the Mobile Workshop"],
    ["recon-drone-orchard","The Orchard Drone","A farm child who found a crashed reconnaissance drone","The Enemy Drone Landed Intact in an Orchard","Its camera module still records and the recovery beacon is active. A patrol will arrive when the beacon is acknowledged.","Recover the Camera Core","Turn the Beacon into an Ambush Sensor"],
    ["bogged-tank","The Tank in the Peat Cut","A recovery sergeant measuring a bogged enemy tank","A New Enemy Tank Is Immobilized but Undamaged","The crew abandoned it after the track sank below the hull. Two tractors can extract it before dawn if the approach road holds.","Recover the Tank Intact","Remove the Gun and Optics"],
    ["pontoon-drift","The Drifting Pontoon Park","A river pilot tracking loose military pontoons","A Complete Pontoon Park Is Drifting Downstream","Floodwater tore the equipment from an enemy depot. The pilot can ground it on the friendly bank or sink it before the enemy launches recovery boats.","Ground the Pontoon Park","Salvage Only the Powered Sections"],
    ["cipher-truck","The Cipher Truck at Milepost 18","A motorcycle scout watching an overturned staff vehicle","An Enemy Cipher Truck Rolled Beyond Its Escort","The guards are injured and the burn detail has not arrived. The truck carries current keying equipment and a map safe.","Capture the Cipher Equipment","Photograph the Map Safe and Withdraw"],
    ["shell-railcar","The Uncoupled Shell Car","A yard worker beside a misrouted ammunition wagon","A Railcar of Enemy Shells Is Standing on a Civilian Siding","The manifest is wrong and no unit claims the car. A switch engine can move it into friendly custody before the afternoon inventory.","Seize the Ammunition Wagon","Replace the Shells with Ballast"],
    ["hospital-generators","The Field Hospital Generators","A surgical orderly left behind during evacuation","Three Mobile Generators Remain in an Evacuated Hospital","The enemy removed the patients but not the power trailers. The orderly knows which unit holds spare regulators and sterile cable.","Recover the Generator Train","Strip the Regulators and Cable"],
    ["radar-van","The Silent Radar Van","A radio technician monitoring an abandoned hilltop","An Enemy Radar Van Is Broadcasting Its Test Pattern","The crew has moved downslope during a fire, leaving the transmitter, processing rack, and manuals under automatic test.","Capture the Processing Rack","Copy the Waveform Library"],
    ["fuel-bladders","The Orchard Fuel Farm","A reconnaissance pair counting camouflaged fuel bladders","A Forward Fuel Farm Has No Permanent Guard","The convoy escort leaves before the receiving unit arrives. Pumps, bladders, and filters sit unattended for thirty-eight minutes.","Capture the Fuel Farm","Contaminate the Filters and Take the Pumps"],
    ["workshop-barge","The Workshop Barge","A tug engineer who recognizes a disguised repair vessel","The Civilian Barge Carries an Armored Repair Shop","Machine tools, track blocks, and recovery winches are hidden beneath timber. The tug crew will defect if the barge crosses the channel tonight.","Bring the Workshop Barge Across","Extract the Crew and Critical Tools"],
  ]),
  ...group("energy-warfare","soe // resistance",[
    ["load-dispatcher","The Load Dispatcher's Pencil","A grid dispatcher on the midnight board","The Enemy Rail District Has One Unprotected Feeder","The dispatcher can shift civilian demand away before dropping the military feeder. The outage will look like overload unless the enemy sees the handwritten board.","Trip the Military Feeder","Map the Emergency Switching Plan"],
    ["turbine-bearing","The Warm Turbine Bearing","A power-station oiler reading a rising temperature","One Turbine Is Carrying the Arsenal District Alone","The bearing will survive tonight if cooled. Withholding one oil line produces a controlled failure after the arsenal night shift starts.","Starve the Bearing Oil","Force an Emergency Shutdown Inspection"],
    ["substation-relay","The Borrowed Protection Relay","A substation apprentice installing a replacement relay","The Replacement Relay Has No Seal","A captured relay can be substituted with altered trip settings. It will disconnect the air-defense grid during the next voltage surge.","Install the Altered Relay","Copy the Protection Settings"],
    ["coal-conveyor","The Coal Conveyor Joint","A conveyor mechanic responsible for the boiler feed","One Coupling Feeds Both Military Boilers","A cracked replacement coupling can be fitted during lunch. Failure will stop coal delivery without damaging the civilian steam loop.","Fit the Cracked Coupling","Seed Metal Fragments in the Crusher"],
    ["penstock-gate","The Penstock Inspection Gate","A dam inspector holding a temporary access order","The Hydroelectric Penstock Is Open for Inspection","The inspector can place charges beside the military turbine intake or leave instruments that reveal every load change for a week.","Cripple the Military Turbine","Instrument the Load Cycle"],
    ["compressor-station","The Compressor Station Picnic","A gas technician attending the superintendent's family picnic","The Front's Gas Compressor Is Running on One Controller","Most staff are outside the perimeter. The technician can remove the controller, destroy it, or copy its calibration before the shift returns.","Remove the Compressor Controller","Corrupt the Calibration Table"],
    ["district-heating","The District Heating Bypass","A heating engineer who designed the buried loop","The Command Bunker Shares a Civilian Heating Bypass","Closing two basement valves isolates the bunker without freezing the surrounding housing blocks. The valves are accessible through a laundry room.","Isolate the Command Bunker","Mark the Buried Service Tunnel"],
    ["black-start-diesel","The Black-Start Diesel","A generator attendant hiding in a switch house","The Capital Grid Has One Black-Start Machine","If the diesel fails after a blackout, the military district cannot restart independently. The attendant can drain its air bottles without touching the hospital reserve.","Bleed the Starting-Air Bottles","Replace the Governor Spring"],
    ["transformer-oil","The Transformer Oil Sample","A laboratory courier carrying a genuine test bottle","A Contaminated Sample Can Condemn the Reserve Transformer","The courier can substitute a sample containing copper and moisture. Safety rules will keep the transformer offline through the offensive window.","Substitute the Failed Sample","Track Where the Reserve Transformer Moves"],
    ["pylon-survey","The Surveyor's Leaning Pylon","A cadastral surveyor documenting subsidence","One Transmission Pylon Already Stands at the Failure Limit","A small cut at the stressed footing will drop the military line in the next high wind. The same survey can instead reveal the repair depots and bypass routes.","Prepare the Wind-Triggered Failure","Follow the Emergency Repair Convoy"],
  ]),
  ...group("political-warfare","resistance // oral-history",[
    ["ration-ledger","The Minister's Ration Ledger","A warehouse auditor with a duplicate ration book","The Enemy Cabinet Has Been Feeding One District Twice","The duplicate entries prove food was diverted to political loyalists while frontline families queued. Publication could split the governing coalition before the budget vote.","Release the Duplicate Ledger","Trade the Ledger for an Informant"],
    ["casualty-printer","The Uncut Casualty Sheets","A print-shop foreman holding unissued casualty rolls","The Enemy Has Hidden an Entire Division's Dead","The sheets were printed and then recalled before cutting. Their numbering proves the official total omitted three weeks of losses.","Distribute the Uncut Rolls","Leak the Numbering Proof to Regional Governors"],
    ["price-decree","The Two Price Decrees","A junior clerk who typed conflicting food decrees","Two Ministries Issued Opposite Price Controls","Both copies bear valid seals. Releasing them together will force the cabinet to choose between urban consumers and farm suppliers.","Publish Both Decrees","Feed Each Decree to a Different Faction"],
    ["governors-wire","The Governors' Private Wire","A telegraphist on the provincial conference circuit","Three Governors Are Coordinating Against the War Cabinet","The governors believe the line is private. Their coalition wants ammunition authority returned to the provinces and may support a negotiated pause.","Encourage the Governors' Bloc","Record the Coalition Before Contact"],
    ["factory-council","The Factory Council Ballot","A toolmaker printing a clandestine ballot","The Arsenal Workers Will Vote on a Slowdown Tonight","The vote can become an organized production strike, an intelligence network, or nothing if outside sponsorship becomes visible.","Finance the Selective Slowdown","Recruit Inspectors from the Ballot Committee"],
    ["newsreel-can","The Missing Newsreel Can","A cinema projectionist holding censored front footage","The Censored Reel Shows the Capital's Brigade Retreating","The footage contradicts the victory bulletin and includes recognizable officers. One screening could ignite panic; controlled excerpts could discredit a single minister.","Arrange a Clandestine Screening","Release Still Frames Against the War Minister"],
    ["synod-letter","The Synod's Sealed Letter","A cathedral archivist carrying an unsigned pastoral draft","The National Synod Is One Signature from Condemning Mobilization","The letter frames conscription as a breach of sanctuary obligations. Securing the last signature could shift rural compliance within hours.","Secure the Final Signature","Circulate the Draft Without Attribution"],
    ["bond-auction","The Failed War-Bond Auction","A bank runner with the real subscription book","The War-Bond Auction Failed Before the State Bought Its Own Paper","The book proves public demand covered less than a quarter of the issue. Revealing it may collapse confidence or force creditors to demand concessions.","Expose the Failed Auction","Use the Book to Split the Creditors"],
    ["port-tariff","The Port Authority's Secret Tariff","A customs broker with the unpublished fee schedule","Neutral Shipping Is Paying the Enemy for Priority","The schedule shows military cargo buying passage through a nominally neutral port. Publication can close the route or drive the port into open alignment.","Expose the Priority Tariff","Threaten Exposure for Transit Access"],
    ["mayors-petition","The Mayors' Carbon Copy","A municipal secretary preserving a rejected petition","Forty-Two Mayors Asked the Cabinet to End Forced Requisitions","The government destroyed the signed original but missed the carbon. The signatories form a ready domestic opposition if contacted before arrests begin.","Activate the Mayors' Coalition","Warn the Signatories and Map the Arrest Teams"],
  ]),
  ...group("leadership-interdiction","special-operations // resistance",[
    ["governor-motorcade","The Governor's Repeated Turn","A traffic constable assigned to the governor's route","The Civil Governor's Motorcade Makes the Same Unprotected Turn","Roadworks force the convoy to slow beside an empty printing house. The constable can hold the cross traffic for an attack or use the route to place a tracker.","Authorize the Leadership Strike","Track the Governor to the Continuity Site"],
    ["finance-wedding","The Finance Commissioner's Wedding","A hotel steward setting the private dining room","The War-Finance Commissioner Will Attend Without His Guard Detail","The guest list includes bond brokers and cabinet couriers. The room can be attacked, bugged, or left untouched at significant political cost.","Target the Commissioner","Record the Brokers' Commitments"],
    ["broadcast-balcony","The Broadcaster's Balcony","A stage electrician above the state radio balcony","The Regime's Civilian Broadcaster Is Rehearsing Alone","The broadcaster coordinates mobilization appeals and casualty denial. The electrician controls the lift, lights, and an unsecured service stair.","Interdict the Broadcast Director","Replace the Address with a False Mobilization Order"],
    ["minister-vent","The Minister's Ventilation Shaft","A maintenance worker inside the emergency cabinet complex","The Armaments Minister's Shelter Has an Unscreened Intake","The intake reaches the minister's office but also serves two clerical rooms. Any attack is attributable if investigators recover the maintenance roster.","Authorize the Shelter Attack","Install an Acoustic Pickup"],
    ["party-secretary-clinic","The Party Secretary's Clinic Visit","A nurse holding the weekly appointment book","The Ruling Party Secretary Visits a Civilian Clinic Every Thursday","The secretary arrives before security sweeps the adjacent laundry. Removing him may fracture mobilization authority or trigger collective punishment.","Target the Party Secretary","Copy the Appointment Book and Build a Pattern"],
    ["procurement-inspection","The Procurement Chairman's Factory Tour","A safety inspector controlling the plant alarm","The Procurement Chairman Will Cross the Foundry Floor During a Drill","The inspector can isolate the delegation between fire doors. The same access could secure the chairman's briefcase without killing him.","Close the Fire Doors on the Delegation","Take the Procurement Briefcase"],
    ["occupation-mayor-rail","The Occupation Mayor's Railcar","A dining-car attendant on the mayor's weekly train","The Occupation Mayor Travels in an Unmarked Dining Car","The guard rides two cars forward because the mayor dislikes uniforms at dinner. A tunnel stop offers a clean interception and a difficult escape.","Seize the Mayor at the Tunnel Stop","Photograph His Traveling Archive"],
    ["chief-censor-premiere","The Chief Censor's Premiere","A projection mechanic beneath the state theater","The Chief Censor Will Sit Above an Unlocked Machinery Room","The machinery room reaches the private box through a service lift. The audience includes foreign press, making every outcome politically amplified.","Interdict the Chief Censor","Trap the Censor with the Banned Reel"],
    ["militia-patron-funeral","The Militia Patron's Funeral","A cemetery keeper controlling the service gate","The Civilian Patron of Three Militias Will Attend the Burial","His guards must leave weapons at the chapel entrance. Capturing him could expose payrolls; killing him could unify otherwise rival militias.","Capture the Militia Patron","Mark and Follow the Paymasters"],
    ["cabinet-courier-villa","The Cabinet Courier's Villa","A groundskeeper who found the courier's overnight bag","A Cabinet Courier Is Sleeping Beside the Continuity Orders","The bag contains sealed succession instructions. The courier can be taken, the seals copied, or the entire chain left unaware of compromise.","Capture the Courier and Orders","Copy the Seals and Return the Bag"],
  ]),
  ...group("counterintelligence","lrrp // special-operations",[
    ["pad-reuse","The Reused One-Time Pad","A cryptanalyst comparing two weather messages","Two Enemy Stations Reused the Same Pad Page","The overlap opens both messages and may expose the key schedule. Acting visibly will close a much larger channel.","Exploit the Pad Reuse Now","Preserve the Compromise for Traffic Analysis"],
    ["dead-drop-milk","The Milk-Bottle Dead Drop","A dairy driver who noticed the same sealed bottle","An Enemy Courier Uses the Hospital Milk Route","The bottle moves between a laboratory gate and a rented room. Substitution can feed false reports or identify the receiving officer.","Substitute a False Report","Follow the Receiving Officer"],
    ["inspection-stamps","The Counterfeit Inspection Stamps","A quartermaster comparing depot seals","The Enemy's Sabotage Teams Use One Imperfect Stamp","A broken letter on the seal links six maintenance failures to the same infiltration cell. The next stamped crate is already in transit.","Roll Up the Sabotage Cell","Let the Crate Lead to Its Controller"],
    ["biometric-cache","The Borrowed Handprint","A security technician auditing a captured access panel","One Enemy Officer's Biometric Template Remains Cached","The template can open a command annex once before the system reconciles. It can also reveal which facilities share the same identity database.","Use the Cached Identity","Map the Shared Security Domain"],
    ["paymaster-ledger","The Paymaster's Decimal Error","An accountant reading a captured militia payroll","A Repeated Decimal Identifies the Enemy's Informant Fund","The same transcription error appears in payments across four cities. Matching recipients will expose a national network.","Freeze and Arrest the Paid Agents","Turn the Payment Channel Back on Its Controller"],
    ["direction-finder-gap","The Direction-Finder Lunch Break","A radio operator charting enemy intercept stations","The Enemy Direction-Finding Net Goes Blind for Eleven Minutes","Operators change shifts at different times except during one shared meal delivery. A burst transmission can pass or a false net can be planted.","Transmit the Agent Rollup","Plant a Phantom Headquarters"],
    ["mailbag-ash","The Unburned Mailbag","A postal inspector at a bombed sorting office","The Security Service Burned the Letters but Not the Routing Slips","The slips preserve pseudonyms, postal districts, and frequency. They are enough to reconstruct the censorship chain.","Reconstruct the Censorship Network","Feed Marked Letters into the Chain"],
    ["hotel-register","The Erased Hotel Register","A night clerk who kept the carbon sheet","The Enemy Liaison Delegation Erased Only the Original Register","The carbon lists room pairings and vehicle calls. It can identify who met whom without revealing the hotel source.","Detain the Liaison Delegation","Exploit the Room Pairings Quietly"],
    ["false-deserter","The Deserter Who Knows Tomorrow's Password","A screening sergeant interviewing a suspicious defector","The Deserter Arrived with a Password Not Yet Issued","He is either a valuable source or proof that the friendly password office is compromised. His handler expects a signal by sunset.","Run the Deserter Back at His Handler","Audit and Replace the Password Office"],
    ["camera-clock","The Camera with the Wrong Clock","A photo interpreter comparing reconnaissance negatives","Every Sabotage Photograph Is Exactly Seventeen Minutes Fast","The time error matches one commercial camera shop. Its repair register can identify the photographer before the next target is struck.","Seize the Camera-Shop Register","Watch the Shop for the Photographer"],
  ]),
  ...group("personnel-recovery","oral-history // naval-special-operations",[
    ["downed-observer","The Downed Observer's Mirror","An artillery observer signaling from a flooded field","A Downed Observer Is Flashing the Enemy Gun Line","The observer survived the crash and has counted the batteries hunting him. Floodwater closes the recovery track in less than an hour.","Launch the Floodplain Recovery","Take His Grid by Burst Transmission"],
    ["surveyors-chimney","The Surveyors in the Chimney","Three topographic surveyors hiding in a brick kiln","The Survey Team Can See the Entire Rail Junction","Their rooftop instrument has fixed every switch and siding, but patrol dogs have entered the kiln yard.","Extract the Survey Team","Recover Only the Survey Book"],
    ["partisan-courier","The Courier at the Checkpoint","A partisan courier detained with a blank passport","The Courier Carries the Names in Memorized Verse","No incriminating paper exists, but interrogation will eventually expose the cadence. A prisoner transfer passes the checkpoint once.","Substitute Her into the Prisoner Transfer","Create a Diversion and Burn the Route"],
    ["wounded-listener","The Listener Under the Tower","A wounded signals intelligence operator beside a damaged recorder","The Recorder Holds the Enemy Offensive Net","The operator cannot move without a litter. The recorder can, but only he knows which sections are deliberate deception.","Recover the Operator and Recorder","Transmit His Authentication Notes First"],
    ["escaped-aircrew","The Orchard Aircrew","Four escaped aircrew hiding beneath cider barrels","The Aircrew Saw a New Missile Site from the Ground","Their escape route is compromised, but their sketches could redirect the campaign's air effort if they reach a debriefing room.","Open the Full Escape Line","Send the Sketches with One Courier"],
    ["harbor-diver","The Diver Beneath Pier Six","A naval diver trapped behind a closed security boom","The Diver Has Attached a Tracker to the Command Ship","He can remain hidden until dark, but the tracker battery will reveal itself first. A fishing launch can force the boom at the cost of the harbor network.","Force the Boom and Recover Him","Order Him to Exfiltrate Through the Intake Tunnel"],
    ["dam-engineer","The Engineer in the Gatehouse","A civil engineer refusing to abandon the flood controls","The Engineer Knows Which Levee Can Hold the Retreat","Enemy scouts surround the gatehouse. Without the engineer, opening the wrong sluice could drown the friendly withdrawal route.","Recover the Engineer by Armored Launch","Hold the Gatehouse Until the Withdrawal Passes"],
    ["sniper-pair","The Pair in the Bell Tower","A reconnaissance sniper team cut off above the old square","The Pair Has Identified the Enemy Counterstroke Staff","They can take one shot, continue observing, or descend through a building now being searched floor by floor.","Extract the Pair Through the Roof","Take the Staff Target Before Withdrawal"],
    ["interpreter-bus","The Interpreter on the Evacuation Bus","A local interpreter traveling under a false family name","The Interpreter Can Identify the Enemy Negotiating Team","Security police are checking the bus from the rear. A friendly agent controls the front door for less than two minutes.","Remove the Interpreter at the Front Door","Use Her Identification Before the Bus Is Stopped"],
    ["demolition-team-quarry","The Quarry Demolition Team","A five-person team stranded after cutting the rail line","The Team Still Holds the Unused Charges","Search parties have sealed the roads but not the quarry conveyor. Recovering the team also recovers enough explosive for another mission.","Run the Conveyor Extraction","Cache the Charges and Exfiltrate Individually"],
  ]),
  ...group("domestic-reform","oral-history // special-operations",[
    ["ghost-battalion","The Ghost Battalion Payroll","A payroll examiner who found an impossible unit","Twelve Thousand Soldiers Exist Only on the Pay Ledger","The fictitious battalion consumes rations, replacements, and transport priority. The names trace to three War Department personnel offices.","Dissolve the Ghost Battalion","Turn the Payroll into a Counter-Fraud Trap"],
    ["liaison-desks","The Seven Liaison Desks","A captain carrying the same request between ministries","Seven Offices Are Relaying the Same Artillery Request","No office owns the decision, so every request arrives after the target moves. One signature can collapse the chain into a single fires cell.","Consolidate the Liaison Chain","Embed a Forward Authority Team"],
    ["shell-inspectors","The Shell Inspection Queue","A master inspector standing beside rejected ammunition","Good Shells Are Waiting Longer Than Recruits","Three redundant stamps delay release while frontline batteries ration fire. The inspector can assume personal liability and clear the queue today.","Delegate Final Acceptance to the Master Inspector","Deploy Mobile Inspection Teams"],
    ["rail-priority-board","The Rail Priority Board","A dispatcher holding six contradictory priority warrants","Every Ministry Has Declared Its Freight Essential","The warrants make the timetable impossible and leave military trains stalled behind ceremonial cargo. Abolishing the board creates winners, enemies, and movement.","Give Theater Command Final Rail Priority","Publish One National Freight Schedule"],
    ["officer-replacement","The Untouchable Colonel","A division chief of staff documenting repeated failures","One Colonel Has Lost Three Formations and Kept His Command","Patronage protects him, but the latest after-action report carries signatures from every subordinate commander.","Relieve the Colonel in the Field","Break the Patronage Chain at Personnel Command"],
    ["casualty-notices","The Returned Telegrams","A postal supervisor with thousands of undelivered casualty notices","Families Are Learning of Deaths from Pay Stoppages","The notification bureau uses obsolete addresses and refuses local records. A temporary municipal network could clear the backlog before it becomes a political rupture.","Create Local Casualty Liaison Teams","Merge Pay and Notification Records"],
    ["procurement-twins","The Twin Procurement Contracts","An auditor holding two contracts for the same aircraft","Two Directorates Bought the Same Aircraft Twice","One factory collected both advances and delivered neither order. Cancelling the duplicative authority recovers funds but exposes senior sponsors.","Unify Aircraft Procurement","Seize the Duplicate Advance"],
    ["signal-roster","The Signals Roster Nobody Owns","A warrant officer comparing three incompatible duty lists","Half the Trained Operators Are Guarding Empty Offices","Each headquarters protected its own roster while the frontline network failed. A theater-wide assignment order can move them before bureaucratic appeals arrive.","Centralize Signals Personnel","Form Mobile Relay Detachments"],
    ["reserve-depot","The Reserve Depot's Private War","A logistics major inspecting a depot that refuses requisitions","The Depot Commander Is Hoarding Equipment for a Future Offensive","Serviceable vehicles and radios sit behind paperwork while current formations improvise. The commander claims only the cabinet can break the reserve seal.","Break the Reserve Seal","Replace the Depot Command Staff"],
    ["translation-bureau","The Translation Bureau Bottleneck","A bilingual corporal surrounded by unopened intercepts","Critical Intercepts Wait Behind Ceremonial Speeches","Senior linguists are assigned to propaganda while battlefield traffic expires unread. A personnel refactor can reverse the priority before tonight's intercept batch.","Refactor the Translation Bureau","Attach Linguists Directly to Operations"],
  ]),
];

